### ISSUE TITLE
Support for Terraform 0.13 

### ISSUE THREAD

**Issue by JohnLBevan** [terraform-aws-modules/terraform-aws-iam#102]
Are there any plans to enable support for the latest version of Terraform?
Currently only 0.11 (v1) and 0.12 (v2) are supported.

**Comment by antonbabenko** [comment]
Hi John,

Yes, I am planning to update this repo to support more versions in the very near future.

**Comment by antonbabenko** [comment]
[v2.23.0](https://github.com/terraform-aws-modules/terraform-aws-iam/releases/v2.23.0) has been just released with the support for newer versions (0.12 and newer).

**Comment by JohnLBevan** [comment]
Wow, fast turnaround; thank-you @antonbabenko 👍
