### ISSUE TITLE
Breaking change in 2.26.0 in iam-assumable-role module 

### ISSUE THREAD

**Issue by nladuguie** [terraform-aws-modules/terraform-aws-iam#104]
Changes of this commit https://github.com/terraform-aws-modules/terraform-aws-iam/commit/f34e1035fbb8d5ec2646659eb921ce8933797965#diff-4c5de4a6dab157fe74e11cc36213e70dfcd41643b5d643776cfe1a5abc04350a are breaking changes, forcing people to modify their code using version 2.26.0 of the module iam-assumable-role.
But according to the versioning, it should not cause some breaking change like this, otherwise it should have been release in 3.0.0.

**Comment by llamahunter** [comment]
ditto... hit this too.  Was using ~>2.22, so didn't expect such a breaking change to arrive in a minor version release. Deleted all our iam policy bindings, causing stuff to fail.

**Comment by llamahunter** [comment]
Changed in https://github.com/terraform-aws-modules/terraform-aws-iam/pull/96

**Comment by antonbabenko** [comment]
I agree, will revert now. I didn't think about BC this time :(

**Comment by antonbabenko** [comment]
[v3.1.0](https://github.com/terraform-aws-modules/terraform-aws-iam/releases/v3.1.0) has been just released, while
[v2.25.0](https://github.com/terraform-aws-modules/terraform-aws-iam/releases/v2.25.0) is the latest in v2.

Apologize for the confusion.

**Comment by llamahunter** [comment]
The top level README.md probably needs updates to show the newly required `number_of_role_policy_arns` and `number_of_custom_role_policy_arns` variables.  Current examples won't work.

**Comment by llamahunter** [comment]
Well, I guess they will, since they say `version = "~> 2.0"`, but probably should update that to 3.0, and fix the examples.

**Comment by antonbabenko** [comment]
Good catch. Fixed in #105, released [v3.2.0](https://github.com/terraform-aws-modules/terraform-aws-iam/releases/v3.2.0).
