### ISSUE TITLE
iam-assumable-roles-with-saml: Allow for multiple provider ids

### ISSUE THREAD

**Issue by ravanapel** [terraform-aws-modules/terraform-aws-iam#109]
### Issue
The aws_iam_policy_document has support for specifying multiple principle federated identifiers like this:
```
"Principal": {
  "Federated": [
    "arn:aws:iam::012345678912:saml-provider/first",
    "arn:aws:iam::012345678912:saml-provider/second"
  ]
},
```

Currently, this module only supports specifying one provider_id:
```
principals {
  type        = "Federated"
  identifiers = [var.provider_id]
}
```
### Request
Would it be possible to support multiple providers by changing the input variables from `string` to list(string)`? I am willing to have a shot at this, but I don't feel confident in estimating the amount of effort it would take.

**Comment by antonbabenko** [comment]
Good idea. You need to change the input variable type and make it backward compatible. See [this module](https://github.com/terraform-aws-modules/terraform-aws-iam/blob/master/modules/iam-assumable-role-with-oidc/main.tf#L5) for similar evolution.

**Comment by ravanapel** [comment]
Something like this? Will test it at a later moment.

**Comment by ravanapel** [comment]
Thanks!
