### ISSUE TITLE
Add support for SSH Key uploads

### ISSUE THREAD

**Issue by Moncky** [terraform-aws-modules/terraform-aws-iam#11]
Currently unable to upload a users SSH key to their IAM profile.  This should be an option as it is needed for some functionality, such as enabling users to access codecommit

**Comment by Moncky** [comment]
I've submitted a pull request to have this functiionality added 
#12

**Comment by antonbabenko** [comment]
Thank you, Callum, for the contribution!

[v0.0.7](https://github.com/terraform-aws-modules/terraform-aws-iam/releases/v0.0.7) has been released.
