### ISSUE TITLE
purpose of number_of_role_policy_arns and number_of_custom_role_policy_arns?

### ISSUE THREAD

**Issue by Justin-DynamicD** [terraform-aws-modules/terraform-aws-iam#112]
Question in the title, but I don't see a usable purpose for these two settings?  WHat's the usecase?

Currently the value is just for a count, but as Terraform is declarative, providing the count won't guarantess _which_ role policies get applied, just that "n" will.  So unless you match this value to the coresponding list values, you end up wit han effectively random deployment.

With that in mind, it seems more reliable to simply supply this with length(var.role_policy_arns), and ommit these entires entirely, unless there's a purpose Im not seeing?

**Comment by antonbabenko** [comment]
Look at the discussion in #95 for the explanation.

In short, Terraform doesn't support computed values in the count so we need to tell precisely the number of resources to create.

**Comment by Justin-DynamicD** [comment]
Is this a limitation in older Terraform?  Because in 0.13 that statement is simply untrue:

```
locals {
  sample = ["thing1", "thing2"]
}

resource "local_file" "catinthehat" {
    count = length(local.sample)
    content     = local.sample[count.index]
    filename = "${path.module}/foo-${count.index}.bar"
}
```

and the output:

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # local_file.mystery[0] will be created
  + resource "local_file" "catinthehat" {
      + content              = "thing1"
      + directory_permission = "0777"
      + file_permission      = "0777"
      + filename             = "./foo-0.bar"
      + id                   = (known after apply)
    }

  # local_file.mystery[1] will be created
  + resource "local_file" "catinthehat" {
      + content              = "thing2"
      + directory_permission = "0777"
      + file_permission      = "0777"
      + filename             = "./foo-1.bar"
      + id                   = (known after apply)
    }

Plan: 2 to add, 0 to change, 0 to destroy
```

Honestly this isn't really the best way to do it, I would rather do it with a for_each which will allow updates to be a bit more specific so people can add/remove from the list and only create changes for those elements that change:

```
locals {
  sample = ["thing1", "thing2"]
}

resource "local_file" "catinthehat" {
    for_each = toset(local.sample)
    content  = each.value
    filename = "${path.module}/file-${each.key}.bar"
}
```
