### ISSUE TITLE
Output role id from iam-assumable-role

### ISSUE THREAD

**Issue by v-stickykeys** [terraform-aws-modules/terraform-aws-iam#117]
The id of the role is sometimes needed so it would be convenient to have it as an additional output.

See terraform attribute here: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_role_policy#id

```
id - The role policy ID, in the form of role_name:role_policy_name.
```

Happy to submit a pr if that's easiest.

**Comment by antonbabenko** [comment]
Good idea, yes, PR and updated example would be great.
