### ISSUE TITLE
Support specifying a custom assume role policy

### ISSUE THREAD

**Issue by chancez** [terraform-aws-modules/terraform-aws-iam#118]
Hey, I've been using this module for quite a while,a nd we're heavy users of `modules/iam-assumable-role`. One thing I've been working on though, is adding more restrictions to some roles and I'd like to enforce this at the assume role policy level in some cases. Would you be open to a PR that allows specifying the `assume_role_policy` or would you prefer something which makes the `dynamic "condition"` in the `aws_iam_policy_document` more flexible?  If you were open to one of those approaches I would be glad to take up the implementation once it's decided what path to take.

**Comment by anagarjunr** [comment]
looking for the same thing here
want to add some conditions to assume-role and would be great if `modules/iam-assumable-role` can do that

**Comment by adborden** [comment]
Having full control over the policy document would cover a lot of cases. We're using SAML federation and the `iam-assumable-role-with-saml` module but want to specify additional trusted actions (`sts:SetSourceIdentity`), as well as specifying conditions on `sts:SourceIdenity`.

**Comment by simonweil** [comment]
Checkout #176
