### ISSUE TITLE
How to stay in sync when users replace their access keys?

### ISSUE THREAD

**Issue by davidham** [terraform-aws-modules/terraform-aws-iam#13]
I created some users with this module, but I also gave them permission to manage their own access keys. One of my users rotated his keys and now `terraform plan` shows that it wants to create another access key for him. Whats the best way for me to make sure my state is up to date without creating a new key for this user?

**Comment by antonbabenko** [comment]
Hi David!

Normally, if you want users to manage their own AWS access keys themselves you don't need to create those for them by specifying `create_iam_access_key = false`. Users will be able to create them once when login to AWS console.
