### ISSUE TITLE
Is there a way to specify a team name for pgp_key instead of keybase username?

### ISSUE THREAD

**Issue by sharath-yml** [terraform-aws-modules/terraform-aws-iam#14]
Presently, it is creating a dependency on one person to decrypt the encrypted values given through the module as output.
We want to allow everyone in a team to be able to decrypt the outputs such as secrets produced through Terraform. Is this feature planned? or is there some way to achieve this already?

**Comment by antonbabenko** [comment]
Hi @sharath-yml !

This module creates IAM users passwords which can be decrypted with provided PGP keys ([read this](https://github.com/terraform-aws-modules/terraform-aws-iam/tree/master/modules/iam-user#notes-for-keybase-users)).

If you want users to be able to decrypt their own passwords they have to specify their own PGP keys as `pgp_key` argument to the module ([see inputs](https://github.com/terraform-aws-modules/terraform-aws-iam/tree/master/modules/iam-user#inputs)).

Hope it helps.

**Comment by antonbabenko** [comment]
Also, if you need to use not unique PGP keys, but some kind of team name I would recommend to look into what [keybase.io](https://keybase.io) has to offer. I personally have never used teams before.
