### ISSUE TITLE
Please help me with resource "aws_iam_instance_profile"

### ISSUE THREAD

**Issue by ValeriKehayov** [terraform-aws-modules/terraform-aws-iam#140]
Hello guys, 
Could you please help me to create iam_instance_profile with provided module.
I am using iam-assumable-role module:

the policy is created successfully: 

```module "wireguard_iam_policy" {
  source = "../../../modules/iam/modules/iam-policy"

  name        = "Wireguard-policy"
  path        = "/"
  description = "Wireguard Policy"

  policy = <<EOF
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "s3:*",
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "iam:PassRole",
                "iam:ListInstanceProfiles",
                "ec2:*"
            ],
            "Resource": "*"
        }
    ]
}
EOF
}
```
The role and the attachment are also created: 
```module "wireguard_role" {
  source = "../../../modules/iam/modules/iam-assumable-role"

  create_instance_profile = true
  create_role             = true
  role_name               = "Wireguard_Role"
  role_description        = "Wireguard Role to access specific s3 Bucket"
  trusted_role_arns = ["arn:aws:iam::111111111111:user/valeri"]
  custom_role_policy_arns = [module.wireguard_iam_policy.arn]
  number_of_custom_role_policy_arns = 1
}
```
Unfortunately when I attach the role to the ec2 instance, the role is not working and I don't have access to S3 for example. I am not sure why.

Or please, update the example file with EC2 Instance role, policy and attachment.

Thank you.

**Comment by antonbabenko** [comment]
Hi,

`aws_iam_instance_profile` is not created as part of this module, but I think it would be a good addition to the module to have support for such a simple resource, too.

Meanwhile, you can create `aws_iam_instance_profile` resource manually as described [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_instance_profile).

**Comment by ValeriKehayov** [comment]
Hey, 
Thanks for the quick response. 
Yup it will be nice :)

**Comment by cezarmathe** [comment]
Hello!

Isn't this fixed?

https://github.com/terraform-aws-modules/terraform-aws-iam/blob/9278e6f02d64ad8f5e569637bc1323b04c032e92/modules/iam-assumable-role/main.tf#L115-L122

**Comment by antonbabenko** [comment]
@cezarmathe Good question :)

Apparently, `create_instance_profile = true` should be specified as a module argument. This issue can be closed.
