### ISSUE TITLE
Expose aws_iam_role.unique_id in module outputs

### ISSUE THREAD

**Issue by jtyberg** [terraform-aws-modules/terraform-aws-iam#141]
## Is your request related to a new offering from AWS?
No.

## Is your request related to a problem? Please describe.
It would be great if the terraform-aws-iam modules expose the same output variables that the underlying [AWS provider's aws_iam_role](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_role) does.

In particular, we would like to access the `unique_id` attribute output by `aws_iam_role`. This would allow us to create policies based on the IAM role ID, as described [here](https://aws.amazon.com/blogs/security/how-to-restrict-amazon-s3-bucket-access-to-a-specific-iam-role/).

## Describe the solution you'd like.
Add [unique_id](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_role#unique_id) as an output variable of all relevant modules. We are using [iam-assumable-role-with-saml](https://github.com/terraform-aws-modules/terraform-aws-iam/tree/master/modules/iam-assumable-role-with-saml), but it would be great if all modules had consistent outputs.

## Describe alternatives you've considered.
- Stop using the modules in this repo and produce our own terraform to do same. This would give us access to the AWS provider outputs.

## Additional context
None

**Comment by antonbabenko** [comment]
Thanks for the proposal, PR is welcome.
