### ISSUE TITLE
tolist() function does not accept string

### ISSUE THREAD

**Issue by okgolove** [terraform-aws-modules/terraform-aws-iam#154]
## Description

It seems tolist() function does not support converting string to list.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

 - Terraform:
```
Terraform v0.15.1
on darwin_amd64
```
- Provider(s):
```
+ provider registry.terraform.io/hashicorp/aws v3.41.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.2.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```
 - Module: **terraform-aws-modules/iam/aws//modules/iam-assumable-role**

## Reproduction

Just try to create an assumable role with **role_sts_externalid**

### Code Snippet to Reproduce
```
module "my_role" {
  source  = "terraform-aws-modules/iam/aws//modules/iam-assumable-role"
  version = "~> 4.0"

  create_instance_profile = true
  create_role             = true
  role_name         = "pmc"
  role_requires_mfa = false

  trusted_role_arns   = ["arn:aws:iam::<id>:root"]
  role_sts_externalid = "<stsexternalid>"
}
```

[One of the examples ](https://github.com/terraform-aws-modules/terraform-aws-iam/blob/master/examples/iam-assumable-role/main.tf#L51) does not work as well.

## Expected behavior
Role is created successfully

## Actual behavior
Fail:
```
│ Error: Invalid function argument
│
│   on .terraform/modules/my_role/modules/iam-assumable-role/main.tf line 2, in locals:
│    2:   role_sts_externalid = flatten(tolist(var.role_sts_externalid))
│     ├────────────────
│     │ var.role_sts_externalid is "blablabla"
```

### Terminal Output Screenshot(s)
<img width="960" alt="image" src="https://user-images.githubusercontent.com/36846182/119274615-7a7abb00-bc19-11eb-972e-edf83505001b.png">

## Additional context

**role_sts_externalid** variable MUST be a list.

**Comment by antonbabenko** [comment]
Thanks for reporting this issue. [v4.2.0](https://github.com/terraform-aws-modules/terraform-aws-iam/releases/v4.2.0) has been just released.
