### ISSUE TITLE
Unable to get iam_Role_name

### ISSUE THREAD

**Issue by tnimni** [terraform-aws-modules/terraform-aws-iam#156]
## Description

Please provide a clear and concise description of the issue you are encountering, your current setup, and what steps led up to the issue. If you can provide a reproduction, that will help tremendously.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

 - Terraform:
Terraform v0.15.5
on darwin_amd64
 - Provider(s):
+ provider registry.terraform.io/hashicorp/aws v3.44.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.3.1
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1
 - Module:

## Reproduction

 no
 yes

run the code 

### Code Snippet to Reproduce

module "assumable_role" {
  count                         = var.enable_irsa ? 1 : 0
  source                        = "terraform-aws-modules/iam/aws//modules/iam-assumable-role-with-oidc"
  version                       = "v4.1.0"
  create_role                   = false
  role_name                     = join("_", [var.cluster_name, "vpc_cni_addon"])
  provider_url                  = replace(var.cluster_oidc_issuer_url, "https://", "")
  role_policy_arns              = ["arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"]
  oidc_fully_qualified_subjects = ["system:serviceaccount:kube-system:aws-node"]

  depends_on = [
    var.eks_depends_on
  ]
}

output "iam_role_arn" {
  description = "role arn"
  value       = module.assumable_role.iam_role_arn
}

## Expected behavior
Able to get output
## Actual behavior

Error: Unsupported attribute
│
│   on ../terraform-aws-eks/modules/addons/outputs.tf line 3, in output "iam_role_arn":
│    3:   value       = module.assumable_role.iam_role_arn
│     ├────────────────
│     │ module.assumable_role is a list of object, known only after apply
│
│ This value does not have any attributes.
╵

### Terminal Output Screenshot(s)

Error: Unsupported attribute
│
│   on ../terraform-aws-eks/modules/addons/outputs.tf line 3, in output "iam_role_arn":
│    3:   value       = module.assumable_role.iam_role_arn
│     ├────────────────
│     │ module.assumable_role is a list of object, known only after apply
│
│ This value does not have any attributes.
╵

**Comment by king131** [comment]
same issue

**Comment by king131** [comment]
> same issue

Sorry. I found the reason. The older version module was been applied.Correct the lastet version solve this problem.
