### ISSUE TITLE
add aws_iam_user_policy_attachment resource

### ISSUE THREAD

**Issue by rodosskiand** [terraform-aws-modules/terraform-aws-iam#166]
Hi! I want to attach a policy to IAM user with this module. But I noticed, that there missed ```aws_iam_user_policy_attachment``` resource. Do there exist reasons why this resource wasn't added to this module? It seems this issue can be resolved like there: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_user_policy_attachment. 
But this interested, will be this solution correct or should I use IAM flow with sts and roles? 

Thnks!

**Comment by antonbabenko** [comment]
Hi!

The IAM modules are making small and rather fine-grained part of the infrastructure. If you want to use this module, you will need to combine module outputs with other resources outside of the module.

These modules are small on purpose and we won't be adding more logic there.

**Comment by g4rb1** [comment]
@rodosskiand What I'd do in this case is create a new group with only 1 member and attach the policy to the group instead of the user itself, it's proven to scale a lot better for me. Example
```HCL
module "group_with_one_member" {
  source  = "terraform-aws-modules/iam/aws//modules/iam-group-with-policies"
  version = "~> 4"

  name         = "Groupwith1memeber"
  
  group_users = [
    module.iam_user1.iam_user_name,
  ]

  custom_group_policy_arns = [
    "arn:aws:iam::aws:policy/Apolicy",
  ]
}        
```
