### ISSUE TITLE
Adding variable assume_role_policy to module that allowin override

### ISSUE THREAD

**Issue by tcharewicz** [terraform-aws-modules/terraform-aws-iam#168]
## Is your request related to a problem? Please describe.
I would like to use advanced versions of assume role policy document, for example with sts:tagsession at action level or with  conditions.

## Describe the solution you'd like.
Adding variable assume_role_policy, and use it at data policy document level as a override_json.
```
 data "aws_iam_policy_document" "assume_role" {
  override_json = var.assume_role_policy

  statement {
    sid    = "default"
    effect = "Allow"

    actions = [
      "sts:AssumeRole"
    ]

    principals {
      type        = "AWS"
      identifiers = var.trusted_role_arns
    }
  }
}
```

## Additional context
Terraform documentation how override_json works.
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_policy_document

**Comment by antonbabenko** [comment]
Which submodule do you mean we should update?

BTW here is a similar PR where assume_role_policy can be customized - https://github.com/terraform-aws-modules/terraform-aws-lambda/pull/203

**Comment by tcharewicz** [comment]
I have a fork from this module, and I add this option to iam-assumable-roles  but I think it could be added as well to other modules where role or roles are created.

**Comment by antonbabenko** [comment]
It is important to not over-engineer the solution and add unnecessary features. PR is welcome.
