### ISSUE TITLE
What happened to the iam-group-with-assumable-roles-policy module?

### ISSUE THREAD

**Issue by eengelking** [terraform-aws-modules/terraform-aws-iam#17]
The documentation refers to the `iam-group-with-assumable-roles-policy` module, but it doesn't exist.  Looking through the releases, it doesn't look like it ever has.

**Comment by antonbabenko** [comment]
You are right, this module does not exist.

I don't have immediate plans to continue working on this module in the near future.

**Comment by antonbabenko** [comment]
@eengelking [v0.2.0](https://github.com/terraform-aws-modules/terraform-aws-iam/releases/v0.2.0) has been just released. There are many improvements including the one you've asked about.

For exact example of how to use iam-group-with-assumable-roles-policy module check this file - https://github.com/terraform-aws-modules/terraform-aws-iam/blob/master/examples/iam-group-with-assumable-roles-policy/main.tf

**Comment by eengelking** [comment]
@antonbabenko Thank you very, very much!
