### ISSUE TITLE
MalformedPolicyDocument encountered when using iam_eks_role

### ISSUE THREAD

**Issue by hlmuludiang** [terraform-aws-modules/terraform-aws-iam#181]
## Description

I'm using iam_eks_role to create a role for my eks cluster; however I keep getting an error when terraform tries to create the role.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

 - Terraform:

 - Provider(s):
 Terraform v1.1.4
on linux_amd64

 - Module: registry.terraform.io/hashicorp/aws v3.72.0

### Code Snippet to Reproduce

module "iam_eks_role" {
  source           = "terraform-aws-modules/iam/aws//modules/iam-eks-role"
  role_name        = "${var.cluster_name}-eks-service-role"
  role_description = "Service role for ${var.cluster_name} cluster"
  create_role      = var.create_service_role
  version          = "~> 4"

  role_policy_arns = [
    "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy",
  ]
  force_detach_policies = true

  tags = {
    Name    = "eks-role",
    Cluster = var.cluster_name
  }

}

resource "aws_eks_cluster" "wcf_cluster" { ... }

## Expected behavior

 IAM role for the eks cluster created

## Actual behavior

Error encountered creating IAM role

### Terminal Output Screenshot(s)

╷
│ Error: error creating IAM Role (devops-blue-eks-service-role): MalformedPolicyDocument: Could not parse the policy: Statement is not well formatted.
│ 	status code: 400, request id: c2524eb6-b3fb-42ff-8d9e-3c2dc1bb72b8
│ 
│   with module.iam_eks_role.aws_iam_role.this[0],
│   on .terraform/modules/iam_eks_role/modules/iam-eks-role/main.tf line 61, in resource "aws_iam_role" "this":
│   61: resource "aws_iam_role" "this" {
│ 
╵

**Comment by antonbabenko** [comment]
You need to specify `cluster_service_accounts` and/or `provider_url_sa_pairs`.

Please see examples in `iam-eks-role`:

https://github.com/terraform-aws-modules/terraform-aws-iam/blob/7bb7652104bd97b76c47ebad60c0531d359d65de/examples/iam-eks-role/main.tf#L9-L23

**Comment by antonbabenko** [comment]
This issue has been resolved in version 4.10.1 :tada:
