### ISSUE TITLE
not able to get output for "iam_access_key_id"

### ISSUE THREAD

**Issue by Manoj-07** [terraform-aws-modules/terraform-aws-iam#187]
while I am trying to create I am user I am getting "iam_access_key_id" as empty value 
![image](https://user-images.githubusercontent.com/64740477/152391921-e4eb611c-5705-4ea3-9a38-de9ff93830c0.png)
could you please help me to resolve the issue.

**Comment by antonbabenko** [comment]
Could you please open an issue and provide all the details we are asking [there](https://github.com/terraform-aws-modules/terraform-aws-iam/issues/new?assignees=&labels=&template=bug_report.md) (incl. code snippets)?
