### ISSUE TITLE
module iam-role-for-service-accounts-eks missing required policy

### ISSUE THREAD

**Issue by ShyWiz** [terraform-aws-modules/terraform-aws-iam#195]
## Description

Need to add missing permission to the IAM policy generated in the module iam-role-for-service-accounts-eks.

Permission denied error from AWS cluster-autoscaler.
```
aws_cloud_provider.go:369] Failed to generate AWS EC2 Instance Types: UnauthorizedOperation: You are not authorized to perform this operation.
        status code: 403
```
Turns out this action was added to the autoscaler [readme](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md) required permissions which is referenced by this [module's policies.tf file](https://github.com/terraform-aws-modules/terraform-aws-iam/blob/v4.13.1/modules/iam-role-for-service-accounts-eks/policies.tf) but needs to be updated. This required permission was added to that readme in [December](https://github.com/kubernetes/autoscaler/commit/a1faeddbe70146385a8afd4fdcd2cefc8d6fbca7).

## Versions

- Terraform module iam-role-for-service-accounts-eks v4.13.1
- Helm chart for [cluster-autoscaler](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler) version: 9.16.0

**Comment by bryantbiggs** [comment]
hmm, we patched this but it looks like the CI didn't trigger the release https://github.com/terraform-aws-modules/terraform-aws-iam/blob/0ac7f4d0c84319371ca301592a2295d306a925e8/modules/iam-role-for-service-accounts-eks/policies.tf#L23

**Comment by DanielTeraSky** [comment]
@bryantbiggs It looks like the `semantic-release/commit-analyzer` didn't trigger the release as the commit message didn't contain `fix`/`feat`

**Comment by bryantbiggs** [comment]
ah good point, I've got a no-op PR opened that should trigger the release workflow so the patch fix is released this time
