### ISSUE TITLE
[iam-role-for-service-accounts-eks] Cluster ID isn't used to constrain built in policies

### ISSUE THREAD

**Issue by stevehipwell** [terraform-aws-modules/terraform-aws-iam#207]
## Is your request related to a new offering from AWS?
No

## Is your request related to a problem? Please describe.
This module doesn't constrain the built in service policies by the cluster ID/name as is documented in the service deployment documentation. Two services (CA & Karpenter) do have cluster ID inputs but as they're lists this suggests that a shared role is appropriate, which for the services with the highest blast radius should be strongly advised against.

## Describe the solution you'd like.
I'd like to see a cluster ID input for built in policies where it's relevant. I'd also like to see `cluster_autoscaler_cluster_ids` and `karpenter_controller_cluster_ids` changed to be for a single ID. For all other non-idiomatic usage the user should be providing custom policies.

## Describe alternatives you've considered.
I already have this implemented myself, but I was looking to standardise.

## Additional context
n/a

**Comment by bryantbiggs** [comment]
Karpenter was updated with #209
