### ISSUE TITLE
pgp_key listed as optional, but is actually required

### ISSUE THREAD

**Issue by nrmitchi** [terraform-aws-modules/terraform-aws-iam#21]
In the `iam-user` module, the `pgp_key` parameter is listed as not required, and the default is `""`.

In the default case, it is passed into the `aws_iam_user_login_profile`, which *does* required the `pgp_key` (otherwise it raises an exception).

I understand that strictly speaking `pgp_key` is not _always_ required, but in the event you're creating a login profile (which is the default), it is. 

What can we do in order to make this more clear?

**Comment by antonbabenko** [comment]
You are right, you can't create `aws_iam_user_login_profile`without `pgp_key`. It is pretty hard to make it conditional in Terraform 0.11.

There is an example of usage of this module:
https://github.com/terraform-aws-modules/terraform-aws-iam/blob/cd406ccc6ff10ac7c9b8297d96b0251327ba1989/examples/iam-user/main.tf#L25-L35

Let me know if you have ideas on how this can be improved.

**Comment by MeNsaaH** [comment]
@antonbabenko how about just including it in the documentation that, if user is to create a login profile, then gpg key is required?

**Comment by antonbabenko** [comment]
Updated in [v2.8.0](https://github.com/terraform-aws-modules/terraform-aws-iam/releases/v2.8.0) by updating docs.

Closing this issue.
