### ISSUE TITLE
Does not support Terraform Version 1.1.7

### ISSUE THREAD

**Issue by mraslam** [terraform-aws-modules/terraform-aws-iam#210]
## Description

I am trying re-run an existing older version of the Terraform EKS Module 17.1.0 with the latest terraform version and I get an error.

## Versions
 - Terraform:
v1.1.7

### Code Snippet to Reproduce
$ terraform init

## Actual behavior
Module module.iam_assumable_role_admin (from registry.terraform.io/terraform-aws-modules/iam/aws//modules/iam-assumable-role-with-oidc) does not support Terraform version 1.1.7. To proceed, either choose another supported Terraform version
│ or update this version constraint. Version constraints are normally set for good reason, so updating the constraint may lead to other errors or unexpected behavior.

**Comment by bryantbiggs** [comment]
the iam-assumable-role-with-oidc does support v1.1.7 https://github.com/terraform-aws-modules/terraform-aws-iam/blob/691bb9203b4fb970c26a6b1e09379e259cb0e3bd/modules/iam-assumable-role-with-oidc/versions.tf#L2

I suspect you are running into a version conflict with the EKS module at v17.1.0. Please post full config with versions so we can better troubleshoot

**Comment by mraslam** [comment]
@bryantbiggs Thank you for the quick response.

Terraform Version: v1.1.7
Terraform EKS Version: 17.1.0
AWS EKS Version: 1.21

FYI - we updated our terraform version recently and seeing this issue.

**Comment by bryantbiggs** [comment]
and what version of the IAM module are you using? when you initialize, can you run `terraform init -upgrade=true`

**Comment by mraslam** [comment]
$ terraform init -upgrade=true
Upgrading modules...
- eks_app in ../terraform-aws-eks-v17.1.0
- eks_app.fargate in ../terraform-aws-eks-v17.1.0/modules/fargate
- eks_app.node_groups in ../terraform-aws-eks-v17.1.0/modules/node_groups
Downloading registry.terraform.io/terraform-aws-modules/iam/aws 2.14.0 for iam_assumable_role_admin...
- iam_assumable_role_admin in .terraform/modules/iam_assumable_role_admin/modules/iam-assumable-role-with-oidc
╷
│ Error: Unsupported Terraform Core version
│
│   on .terraform/modules/iam_assumable_role_admin/modules/iam-assumable-role-with-oidc/versions.tf line 2, in terraform:
│    2:   required_version = ">= 0.12.6, < 0.14"
│
│ Module module.iam_assumable_role_admin (from registry.terraform.io/terraform-aws-modules/iam/aws//modules/iam-assumable-role-with-oidc) does not support Terraform version 1.1.7. To proceed, either choose another supported Terraform version
│ or update this version constraint. Version constraints are normally set for good reason, so updating the constraint may lead to other errors or unexpected behavior.

**Comment by bryantbiggs** [comment]
this is why information is important - you are using v2.14.0 of the IAM module and currently its on v4.14.0 so you'll need to upgrade your version used

**Comment by mraslam** [comment]
@bryantbiggs  Thank you. It worked.
