### ISSUE TITLE
Explain the differences between iam-role-for-service-accounts-eks and iam-eks-role modules

### ISSUE THREAD

**Issue by nxf5025** [terraform-aws-modules/terraform-aws-iam#219]
## Is your request related to a new offering from AWS?
No

## Is your request related to a problem? Please describe.
It seems like there are duplicate modules with [iam-role-for-service-accounts-eks](https://github.com/terraform-aws-modules/terraform-aws-iam/tree/master/modules/iam-role-for-service-accounts-eks) and [iam-eks-role](https://github.com/terraform-aws-modules/terraform-aws-iam/tree/master/modules/iam-eks-role).

## Describe the solution you'd like.
Documentation needs to be more clear on which route users should take or better yet deprecate one of the modules as there is a lot of overlap.

## Describe alternatives you've considered.
n/a
## Additional context
n/a

**Comment by bryantbiggs** [comment]
context: https://github.com/terraform-aws-modules/terraform-aws-iam/pull/184

**Comment by antonbabenko** [comment]
This issue has been resolved in version 4.23.0 :tada:

**Comment by eherot** [comment]
I think this may have been closed by prematurely. #236 explains the difference between iam-eks-role and iam-assumable-role-with-oidc, but it doesn't mention iam-role-for-service-accounts-eks at all (and as a new user of the project I remain confused about which one to use).
