### ISSUE TITLE
modules/iam-role-for-service-accounts-eks/policies.tf should be arn partition consistent

### ISSUE THREAD

**Issue by xchan** [terraform-aws-modules/terraform-aws-iam#224]
## Description

All aws arn in
modules/iam-role-for-service-accounts-eks/policies.tf 
should be in format such as  arn:${local.partition}:*

With karpenter added recently, the former rule is broken. And error will be raise as follow for partition "aws-cn" and "aws-gov"

 Error: error creating IAM Policy AmazonEKS_Karpenter_Controller_Policy-2022041412360163110000000d: MalformedPolicyDocument: Partition "aws" is not valid for resource "arn:aws:ec2:*:xxx:subnet/*".
│       status code: 400, request id: d5d4e215-5abb-49d2-a0fe-dee528de002d
│ 
│   with module.infra_cluster.module.karpenter_irsa.aws_iam_policy.karpenter_controller[0],
│   on .terraform/modules/infra_cluster.karpenter_irsa/modules/iam-role-for-service-accounts-eks/policies.tf line 584, in resource "aws_iam_policy" "karpenter_controller":
│  584: resource "aws_iam_policy" "karpenter_controller" {

**Comment by bryantbiggs** [comment]
closing due to lack of information. please fill in the issue template as it is structured so that we can properly triage your issue
