### ISSUE TITLE
'count' cannot be computed on 'aws_iam_role_policy_attachment.custom'

### ISSUE THREAD

**Issue by xakraz** [terraform-aws-modules/terraform-aws-iam#24]
## Summary

While trying to use the module ` terraform-aws-modules/iam/aws//modules/iam-assumable-role`, I am facing an issue during `terraform` "compilation" step when I want to use the module in a project that also define the policy to use...

## Code

```
module "my_role" {
  source  = "terraform-aws-modules/iam/aws//modules/iam-assumable-role"
  version = "v0.3.0"

  trusted_role_arns = [
    "arn:aws:iam::ACCOUNT_ID:role/RoleName",
  ]

  create_role = "true"

  role_name         = "NAME"
  role_requires_mfa = false

  custom_role_policy_arns = [
    "${aws_iam_policy.gsn_policy.arn}",
  ]
}
```

## Error

```
* module.XXX.aws_iam_role_policy_attachment.custom: aws_iam_role_policy_attachment.custom: value of 'count' cannot be computed
```

**Comment by antonbabenko** [comment]
Xavier,

Unfortunately, you are right that this is not currently supported. This is the most annoying problem when working with Terraform 0.11 and I don't think I'll be able to find time to improve this module to make this to work.

In the meanwhile, you have to create `aws_iam_policy.gsn_policy` resource before calling this module, and paste ARN of it into the module.

It will be not a problem when using Terraform 0.12.
