### ISSUE TITLE
EKS Service Account `aws-ebs-csi-driver` in `examples/iam-role-for-service-accounts-eks/main.tf`: wrong name?

### ISSUE THREAD

**Issue by qingvincentyin** [terraform-aws-modules/terraform-aws-iam#240]
## Description

- [x ] ✋ I have searched the open/closed issues and my issue is not listed.

Consider this line:

- https://github.com/terraform-aws-modules/terraform-aws-iam/blob/2113ea9a06e19e6993bebcbe51f7e2f3830f5842/examples/iam-role-for-service-accounts-eks/main.tf#L93

I don't understand how that could have worked for you.

Your code above is referencing a Service Account (SA) named `aws-ebs-csi-driver`. But that's not the SA created/used by AWS when adopting the EKS `addon` method. According to [this AWS doc](https://docs.aws.amazon.com/eks/latest/userguide/csi-iam-role.html), AWS uses a different name `ebs-csi-controller-sa` (more on this point later):
> _When the plugin is deployed, it creates and is configured to use a service account that's named ebs-csi-controller-sa._ 

- Sidebar: Using the EKS `addon` method, there doesn't seem to be a way to change that default SA name, and both your sample code above as well as the underlying `terraform-aws-modules/eks/aws` doesn't attempt to change that default name. The only way I'm aware of to change that name is to not use the EKS `addon` method but to switch to the (self managed) [Helm Chart](https://github.com/kubernetes-sigs/aws-ebs-csi-driver) method (which isn't what you're doing.)

Furthermore, despite this IAM role your sample code above created, it isn't used when you finally created the EKS cluster at [the bottom of your sample code](https://github.com/terraform-aws-modules/terraform-aws-iam/blob/2113ea9a06e19e6993bebcbe51f7e2f3830f5842/examples/iam-role-for-service-accounts-eks/main.tf#L363-L378). Specifically, you didn't pass the `cluster_addons` input variable to the module `terraform-aws-modules/eks/aws`. So, this role in your sample code is unproven.

## Versions

```console
$ terraform version
Terraform v1.1.1
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.11.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.10.0
+ provider registry.terraform.io/hashicorp/tls v3.3.0
```
- Module version [Required]: https://github.com/terraform-aws-modules/terraform-aws-iam/releases/tag/v4.23.0

## Reproduction Code [Required]

```console
$ pwd
....../terraform-aws-modules/terraform-aws-iam/examples/iam-role-for-service-accounts-eks

$ terraform apply
...
Plan: 104 to add, 0 to change, 0 to destroy.
...

$ aws eks describe-cluster --name ex-iam-eks-role --region eu-west-1
{
    "cluster": {
        "name": "ex-iam-eks-role",
        "version": "1.21",
        ...


$ aws eks update-kubeconfig --name ex-iam-eks-role --region eu-west-1
...

$ kubectl get sa -n kube-system | grep csi
ebs-csi-controller-sa                1         4m21s
ebs-csi-node-sa                      1         4m21s
```

## Expected behavior

The SA referenced by your [sample code](https://github.com/terraform-aws-modules/terraform-aws-iam/blob/2113ea9a06e19e6993bebcbe51f7e2f3830f5842/examples/iam-role-for-service-accounts-eks/main.tf#L93) should be `ebs-csi-controller-sa` in order to match the list of SA above.

## Actual behavior

The SA referenced by your sample code is `aws-ebs-csi-driver` which doesn't exist in the newly created EKS. Consequently, the IAM role you created references that non-existent SA:

```console
$ aws iam get-role --role-name ebs-csi
{
   ...
        "RoleName": "ebs-csi",
        "AssumeRolePolicyDocument": {
                            ...,
                            "oidc.eks.eu-west-1.amazonaws.com/id/088B5D76161AFEB4CE8FD396C702B490:sub": "system:serviceaccount:kube-system:aws-ebs-csi-driver"
```

**Comment by bryantbiggs** [comment]
while we should default to the default service account used by the addons, the code linked is simply an example and is valid since users are able to change the name of the service account used

**Comment by bryantbiggs** [comment]
> OK, I wish what you just said above had been put as an inline comment in the sample code. That would have avoided common misunderstandings. It isn't clear at all both in the sample code and in the module documentation for `terraform-aws-modules/eks/aws` of how/what to pass that value. I had to read the module's source code -- and experiment with a real execution -- to understand what it does.

I think this is down to the lack of understanding of common Terraform module conventions and understanding of Terraform variables/inputs. 

> Change the SA name to match the reality: ebs-csi-controller-sa. And add an inline comment to link to the AWS docs I mentioned above in order to explain where that magic value comes from.)

Completely reasonable

> Pass the cluster_addons input variable to the module terraform-aws-modules/eks/aws to demonstrate that it actually, indeed works?

We do not validate plugins in this module. I have established the pattern of linking to where the policy is pulled from and the onus is left on the addon to ensure the permissions are correct. When the upstream permissions change, we can change here to reflect but we do not validate their plugins nor their permissions.
