### ISSUE TITLE
Module detecting changes in policy documents on every Terraform Plan. Whitespace 

### ISSUE THREAD

**Issue by thinkbiggerltd** [terraform-aws-modules/terraform-aws-iam#241]
## Description

Since moving to v4.23.0 of the terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks module, I am getting whitespace updates on all policy document resources during plan. The behavior repeats no matter how often the plan/apply is run. The issue is non-disruptive but is not ideal. The issue does not exist in v4.20.3

## Versions

v4.23.0 

- Terraform version: v1.0.7
- Provider version(s):
```hcl
terraform {
  required_version = ">= 0.13.1"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 3.72"
    }
    tls = {
      source  = "hashicorp/tls"
      version = ">= 3.0"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = ">= 2.10"
    }
  }
}
```

## Reproduction Code [Required]

Terraform plan/apply

## Expected behavior

No changes. Your infrastructure matches the configuration.
Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.

## Actual behavior
```hcl
module.eks_cluster.module.efs_csi_controller.aws_iam_role.this[0]
resource "aws_iam_role" "this" {
    assume_role_policy = jsonencode( # whitespace changes
            {
                Statement = [
                    {
                        Action    = "sts:AssumeRoleWithWebIdentity"
                        Condition = {
                            StringEquals = {
                                oidc.eks.us-east-1.amazonaws.com/id/0000000000000000:aud = "sts.amazonaws.com"
                                oidc.eks.us-east-1.amazonaws.com/id/0000000000000000:sub = [
                                    "system:serviceaccount:kube-system:efs-csi-controller-sa",
                                    "system:serviceaccount:kube-system:efs-csi-node-sa",
                                ]
                            }
                        }
                        Effect    = "Allow"
                        Principal = {
                            Federated = "arn:aws:iam::000000000000:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/0000000000000000"
                        }
                        Sid       = ""
                    },
                ]
                Version   = "2012-10-17"
            }
        )
        id                 = "efs-csi-controller"
        name               = "efs-csi-controller"
        mtags              = {}
        (8 unchanged attributes hidden)
        (1 unchanged block hidden)
    }
```

**Comment by iaacautomation** [comment]
Maybe instead of jsonencode a data aws_iam_policy_document" would work better?

**Comment by bryantbiggs** [comment]
we don't use `jsonencode()` and utilize `aws_iam_policy_document` - maybe https://github.com/hashicorp/terraform/pull/30486 will aid with this behavior

**Comment by bryantbiggs** [comment]
Please update to the latest v5.0.0 and let us know if this issue persists. If issue still persists, please provide reproduction code

**Comment by fferguson6** [comment]
Afraid we're still seeing the issue on v5.1.0

## Description

On a plan or apply Terraform consistently detects a change in the `assume_role_policy` of the iam role created in our case it's part of the `iam-role-for-service-accounts-eks` module.

An interesting observation is that this doesn't happen consistently. Subsequent plans will show changes to other invocations of the module which didn't happen previously. We're calling the module 8 times and will always see at least 2 of them detecting changes on any given plan.

## Expected Behaviour

Terraform to detect no changes, as nothing has changed.

## Actual Behaviour

Although Terraform doesn't want to perform any changes it still detects drift in the iam policy where there shouldn't be.

```terraform
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 3.75.0"
    }
}

module "cluster_autoscaler_irsa_role" {
  source = "terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks"
  version = "5.1.0"

  role_name                        = "cluster-autoscaler-${var.cluster_name}"
  role_path                        = "/k8s/kube-system/"
  attach_cluster_autoscaler_policy = true
  cluster_autoscaler_cluster_ids   = [module.eks.cluster_id]

  oidc_providers = {
    main = {
      provider_arn               = module.eks.oidc_provider_arn
      namespace_service_accounts = ["kube-system:cluster-autoscaler"]
    }
  }
}

# module.eks_native[0].module.cluster_autoscaler_irsa_role.aws_iam_role.this[0] has been changed
~ resource "aws_iam_role" "this" {
    ~ assume_role_policy    = jsonencode( # whitespace changes
          {
              Statement = [
                  {
                      Action    = "sts:AssumeRoleWithWebIdentity"
                      Condition = {
                          StringEquals = {
                              oidc.eks.us-west-2.amazonaws.com/id/00000000000000000000000000000000:aud = "sts.amazonaws.com"
                              oidc.eks.us-west-2.amazonaws.com/id/00000000000000000000000000000000:sub = "system:serviceaccount:kube-system:cluster-autoscaler"
                          }
                      }
                      Effect    = "Allow"
                      Principal = {
                          Federated = "arn:aws:iam::00000000000:oidc-provider/oidc.eks.us-west-2.amazonaws.com/id/00000000000000000000000000000000"
                      }
                      Sid       = ""
                  },
              ]
              Version   = "2012-10-17"
          }
      )
      id                    = "cluster-autoscaler-abc-123-abc-1"
      name                  = "cluster-autoscaler-abc-123-abc-1"
      tags                  = {}
      # (8 unchanged attributes hidden)

      # (1 unchanged block hidden)
  }

```

**Comment by bryantbiggs** [comment]
Are you using a `depends_on` dependency?

**Comment by lifelofranco** [comment]
Why was this closed? I'm using the latest version and every plan on this module has a lot of noise. 

![Screen Shot 2022-07-23 at 5 01 11 AM](https://user-images.githubusercontent.com/4952784/180568313-093a156e-9a2a-4732-ba0c-b080f79f7efc.png)

![Screen Shot 2022-07-23 at 5 03 50 AM](https://user-images.githubusercontent.com/4952784/180568343-b58ca1c1-f47c-41e5-b01d-451f56f4ec9b.png)

**Comment by bryantbiggs** [comment]
@lifelofranco whats your reproduction config?

**Comment by lifelofranco** [comment]
I just use `for_each` to use the modules. 

`locals {
    groups = {
      "Admin" = {
        users = [
          "life"
        ]
        policy_arns = ["arn:aws:iam::aws:policy/AdministratorAccess"]
      }
      "Engineering" = {
        users = [ ... ]`
         policy_arns = ["arn:aws:iam::aws:policy/AdministratorAccess"]
       }
}

module "groups" {
  depends_on = [module.users, module.policies]

  source   = "terraform-aws-modules/iam/aws//modules/iam-group-with-policies"
  version  = "5.2.0"
  for_each = local.groups

  attach_iam_self_management_policy = false

  name                     = each.key
  group_users              = each.value.users
  custom_group_policy_arns = each.value.policy_arns
}

module "policies" {
  source   = "terraform-aws-modules/iam/aws//modules/iam-policy"
  version  = "5.2.0"
  for_each = local.policies

  name           = each.key
  path             = "/"
  description = each.value.description
  policy          = templatefile(each.value.policy, try(each.value.policy_vars, {}))
}
`

**Comment by lifelofranco** [comment]
Can we reopen this issue? @bryantbiggs

**Comment by bryantbiggs** [comment]
There isn't anything to do within this module since the issue is not reproducible. I suspect its on your end as to why there are changes (usually because of a `depends_on`)

**Comment by toredash** [comment]
> There isn't anything to do within this module since the issue is not reproducible. I suspect its on your end as to why there are changes (usually because of a `depends_on`)

Can confirm this. I had a `depens_on` that produced the same issue as OP describes.
