### ISSUE TITLE
Sources to use for service accounts

### ISSUE THREAD

**Issue by gfrid** [terraform-aws-modules/terraform-aws-iam#251]
hi,

For this list of supported IAM roles, do i need to use TF code from other sources such as this: https://registry.terraform.io/modules/andreswebs/eks-cert-manager/aws/latest

and pin point the serviceaccount?

there are no examples for any except EBS on this page:
https://github.com/terraform-aws-modules/terraform-aws-iam/tree/master/modules/iam-role-for-service-accounts-eks

**Comment by bryantbiggs** [comment]
The `iam-roles-for-service-accounts-eks` simply provide the IRSA role+policy - the addon, such as cert-manager, is provided by users through either Terraform, kubectl, Helm, etc.

**Comment by gfrid** [comment]
> The `iam-roles-for-service-accounts-eks` simply provide the IRSA role+policy - the addon, such as cert-manager, is provided by users through either Terraform, kubectl, Helm, etc.

thanks
