### ISSUE TITLE
using 5.0 causes "Could not retrieve the list of available versions for provider hashicorp/aws:" error

### ISSUE THREAD

**Issue by sanguis** [terraform-aws-modules/terraform-aws-iam#252]
## Description

when I use

```hcl
module "iam_role_config_remedation" {
  source  = "terraform-aws-modules/iam/aws//modules/iam-assumable-role"
  version = "5.0.0"

  ...
```
I get the error.

`Could not retrieve the list of available versions for provider hashicorp/aws:`

When `init`ing

when I set `version  = "4.24.1"` it works. 

I have tried rming ~/.terraform.d and .terraform and its consistent. I am on an intell mac. I have also run `curl https://registry.terraform.io/v1/providers/hashicorp/aws/versions |jq |less`  to verify that I can get the metadata'

## Versions

- Module version [Required]:
5.0.0

- Terraform version:
Terraform v1.1.9                                                                                                               │
on darwin_amd64                                                                                                                │
                                                                   │
                                                                                                                               

+ provider registry.terraform.io/hashicorp/aws v3.75.1                                                                         │
+ provider registry.terraform.io/hashicorp/external v2.2.2                                                                     │
+ provider registry.terraform.io/hashicorp/local v2.2.3     
## Reproduction Code [Required]

Create call the module with version 5.0.0,
terraform init

## Expected behavior

init to get the provider

## Actual behavior
Errror mentioned above

**Comment by bryantbiggs** [comment]
You most likely have other modules or a version constraint that is conflicting with the version constraints in v5.0

**Comment by max-rocket-internet** [comment]
I've seen this before randomly also. I just removed `.terraform*` (be sure your state is stored remotely!) and re-init.

**Comment by sanguis** [comment]
> You most likely have other modules or a version constraint that is conflicting with the version constraints in v5.0

This seems to be an issue with AWS version 4. I just created a codebase with just
```
terraform {
  required_version = ">= 1.0.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.0"
    }
  }
}
```
In it and got the same error.
