### ISSUE TITLE
Cannot fetch the values of the User while creating multiple users

### ISSUE THREAD

**Issue by sumitG-WAL** [terraform-aws-modules/terraform-aws-iam#253]
I am creating the 10 users using this IAM-user module, but the problem is the output.tf file is not designed to provide the user's related values for multiple user. The only option is to define the output values for every user separately which is not viable as no. of users can be unlimited.

**Comment by antonbabenko** [comment]
This module is not suitable for what you want to do. You can use a suitable data-source to get information about existing user(s). See this, for eg, https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_users
