### ISSUE TITLE
Bad variable type

### ISSUE THREAD

**Issue by Tautcius** [terraform-aws-modules/terraform-aws-iam#254]
## Description

Please provide a clear and concise description of the issue you are encountering, and a reproduction of your configuration (see the `examples/*` directory for references that you can copy+paste and tailor to match your configs if you are unable to copy your exact configuration). The reproduction MUST be executable by running `terraform init && terraform apply` without any further changes.

If your request is for a new feature, please use the `Feature request` template.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

## Versions

- Module version [Required]:

- Terraform version:
1.2.1
- Provider version(s):
aws 3.20.0

## Reproduction Code [Required]

after tf plan i get error: for bad variable type
## Expected behavior

plan should be created

## Actual behavior

i got error

### Terminal Output Screenshot(s)

```bash
│ Error: Invalid value for input variable
│ 
│   on users.tf line 77, in module "iam_eks_role":
│   77:   role_policy_arns = ["arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"]
│ 
│ The given value is not suitable for module.iam_eks_role.var.role_policy_arns declared at .terraform/modules/iam_eks_role/modules/iam-eks-role/variables.tf:37,1-28: map of string required.
```

## Additional context

easy fix
```hcl

variable "role_policy_arns" {
  description = "ARNs of any policies to attach to the IAM role"
  type        = list(string)
  default     = []
}
```

**Comment by bryantbiggs** [comment]
Exactly as @max-rocket-internet stated - checkout the latest docs for v5 where this was updated, let me know if you run into any issues
