### ISSUE TITLE
how to create inline policy w with assumable role

### ISSUE THREAD

**Issue by kapil1699** [terraform-aws-modules/terraform-aws-iam#261]
I want to create inline policy with  assumable role.

Currently,i see it only supports custom policy arn not  inline policy JSON.

Could you please how to create inline policy with assumable role.

My IAM role contains customer managed policy ,aws managed policyband inlinepolicy.

Current module setup only supporting aws and customer mananged policy.

Please suggest.

**Comment by max-rocket-internet** [comment]
@kapil1699 specifically what module are you talking about here?

**Comment by kapil1699** [comment]
@max-rocket-internet : I am using below module reference.

modules/iam-assumable-role/main.tf

**Comment by tomcruz17** [comment]
Doesn't seem possible atm with the `iam-assumable-role`. Would be great to have some variable like:

```
variable "inline_policies" {
  description = "A map of json policies with key = inline_policy_name and value = policy_json"
  type        = map(string)
}
```

@kapil1699 Currently, the workaround would be to use `aws_iam_role_policy` to attach the inline policy:

```
resource "aws_iam_role_policy" "inline_policy" {
  name   = "inline-policy"
  role   = module.created_from_iam_assumable_role.iam_role_name
  policy = <your-policy-json>
}
```

**Comment by kapil1699** [comment]
Can we take this as feature request if it is not possible with current state.

As this is expected for any iam assumable  role to have aws managed, customer manage  and inline policy in same role.


Any other suggestion appriecated.

**Comment by mulebm** [comment]
also interested in this feature! +1
