### ISSUE TITLE
EBS CSI Role permissions are too wide

### ISSUE THREAD

**Issue by huguesalary** [terraform-aws-modules/terraform-aws-iam#266]
## Description

The example policy, which is used by the `iam-role-for-service-accounts-eks` module, provided by the official aws-ebs-csi-driver is too lax (https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/example-iam-policy.json).

This policy presents the following issues:

    It allows the IAM Role to delete any EBS volume tagged with "CSIVolumeName" OR "ebs.csi.aws.com/cluster" OR "kubernetes.io/cluster/*"
    It allows the IAM Role to delete any EBS snapshot tagged with "CSIVolumeSnapshotName" OR "ebs.csi.aws.com/cluster" OR "kubernetes.io/cluster/*"

This means the EBS CSI IAM Role can delete any volume or snapshot from any other cluster.

I am proposing the following PR https://github.com/terraform-aws-modules/terraform-aws-iam/pull/265 which changes this policy and replaces the OR conditions by AND conditions, as well as restricting kubernetes.io/cluster/* to kubernetes.io/cluster/EKS_CLUSTER_ID.

**Comment by bryantbiggs** [comment]
thank you for submitting this! Would you mind opening an issue with the upstream CSI project to see if they would be willing to adopt this spec first? It makes it quite a bit easier to support when the official addon supports it as well. Some addons will have a "general" policy and a "limited"/"strict" policy and then we can follow that strict policy here in the implementation

**Comment by huguesalary** [comment]
No problem! I sent a PR upstream (https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1340).
