### ISSUE TITLE
Support AWS ACK in iam-role-for-service-accounts-eks

### ISSUE THREAD

**Issue by rgarrigue** [terraform-aws-modules/terraform-aws-iam#269]
## Is your request related to a new offering from AWS?

  - Yes ✅, same as the others features in iam-role-for-service-accounts-eks

## Is your request related to a problem? 

No

## Describe the solution you'd like.

AWS ACK allows one to create AWS resources such as a S3 bucket using Kubernetes manifest. It requires some IRSA as described https://aws-controllers-k8s.github.io/community/docs/user-docs/irsa, the recommended policies are documented by controller, [here](https://github.com/aws-controllers-k8s/s3-controller/tree/main/config/iam) for s3, [here](https://github.com/aws-controllers-k8s/rds-controller/tree/main/config/iam) for RDS ...

I'ld like pre-configured roles for those.

## Describe alternatives you've considered.

There's this module https://github.com/DNXLabs/terraform-aws-eks-ack, but we prefer deploying "in kubernetes" resources through ArgoCD, so we just need the IRSA roles. And we are already using the iam-role-for-service-accounts-eks submodule for External DNS & Cert-Manager. I'ld prefer avoid using another 3rd party, not maintained module.

**Comment by bryantbiggs** [comment]
Can't you already do this today?

```hcl
module "irsa_role" {
  source      = "terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks"
  version     = "~> 5.3"
 
  role_name = "name"

  oidc_providers = {
    this = {
      provider_arn               = module.eks.oidc_provider_arn
      namespace_service_accounts = ["<namespace>:<service-account>"]
    }
  }

  role_policy_arns = {
    AmazonS3FullAccess = "arn:aws:iam::aws:policy/AmazonS3FullAccess"
  }

  tags = {}
}
```

**Comment by rgarrigue** [comment]
Indeed. To easy to be worth a pre-configured role. Sorry for the trouble
