### ISSUE TITLE
karpenter_controller_cluster_id is currently a required field but should be made generic

### ISSUE THREAD

**Issue by hawkesn** [terraform-aws-modules/terraform-aws-iam#270]
### Issue:

When provisioning a Karpenter IRSA role without specifying `karpenter_controller_cluster_id`, the IAM policy is set with `Conditions` as follows:
```
...
"Condition": {
    "StringEquals": {
        "ec2:ResourceTag/karpenter.sh/discovery": "*"
    }
},
...
```

Unfortunately, the function `StringEquals` does not accept the `"*"` as a wildcard and it is interpreted literally. 

The JSON editor in the AWS Console also throws warnings:
![image](https://user-images.githubusercontent.com/1168175/186184941-6fef92fe-484f-4398-8a35-d3d179122586.png)

### Potential Solution:
Change all `StringEquals` to `StringLike` in the IAM Policy. This would allow for the wildcard to function as expected.
Referring to AWS doc: https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_String

### Reasoning:
I'm currently using this IRSA module to create a generic Karpenter role where all my k8s clusters in the same AWS account can re-use this. 
Since I'm using GitOps to specify which cluster for Karpenter to use, the constraint is placed there with the goal of the IAM policy to be more open.

The `StringLike` comparison should still allow for backward compatibility with existing tags.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:

- Terraform version:
`Terraform v1.2.7`
- Provider version(s):
`+ provider registry.terraform.io/hashicorp/aws v4.27.0`

## Reproduction Code [Required]

```
module "karpenter_irsa" {
  source  = "terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks"
  version = "5.3.0"

  role_name                          = "IRSA-KarpenterControllerRole"
  attach_karpenter_controller_policy = true
  karpenter_controller_node_iam_role_arns = [
    "arn:aws:iam::${data.aws_caller_identity.current.id}:role/EKSDefaultNodeRole"
  ]
  oidc_providers = local.karpenter_oidc_providers

# In the module, we omit the `karpenter_controller_cluster_id`
}
```

- Terraform Workspaces are in use

1. Provision using the reproduction code above
2. Check the IAM policy

## Expected behavior

No IAM permission errors from Karpenter

## Actual behavior

Karpenter throws: 
```
ERROR    controller.provisioning    Provisioning failed, launching node, creating cloud provider instance, with fleet error(s), UnauthorizedOperation: You are not authorized to perform this operation.
```
Because it's trying to work specifically with resource tags that look like: `"karpenter.sh/discovery": "*"` explicitly

### Terminal Output Screenshot(s)
![image](https://user-images.githubusercontent.com/1168175/186187865-085173f8-33a7-4bb8-8cf5-465da14c97b7.png)

**Comment by bryantbiggs** [comment]
this is intentional - cluster ID is required for proper IAM policy scoping

**Comment by hawkesn** [comment]
Sorry, yes, I guess this should have been a feature request. The `StringLike` parameter would still allow for backwards compatibility for policy scoping, but would also allow for it to be used generically. 

The current pattern that I am using has decoupled the cluster creation and IRSA roles because making IRSA roles per cluster can cause issues with GitOps work. 

For example, if I'm making a "staging cluster A" and then looking to upgrade over to a "staging cluster B", this is relatively easy to do via Terraform - I CAN create two clusters and two IRSA roles (IRSAKarpenterRoleA / IRSAKarpenterRoleB). However, in GitOps, I would have to change the name of all my IRSA roles instead of just using a generic IRSAKarpenterRole. Let me know if that makes sense!

Thanks!

**Comment by hawkesn** [comment]
I managed to find a workaround using the `karpenter_tag_key`. If the `karpenter_controller_cluster_id` is required, may I suggest this change instead:
https://github.com/terraform-aws-modules/terraform-aws-iam/pull/272
