### ISSUE TITLE
AWS provides a managed policy for EBS CSI drive

### ISSUE THREAD

**Issue by obounaim** [terraform-aws-modules/terraform-aws-iam#285]
## Is your request related to a new offering from AWS?
I am not sure if it is a new offering form AWS, but I would say yes. Maybe the managed policy did not exists when this module was first created.

  - Yes ✅: not related to the terraform AWS provider

## Is your request related to a problem? Please describe.

This issue concerns the module iam-role-for-service-accounts-eks. When using this module to create an IAM role for EBS CSI driver, it creates a new customer managed IAM policy. This should be fine, however I just wanted to point out that AWS is already providing a managed policy for EBS driver (maybe you already aware of this, and there is a good reason to not use it).

Managed policy ARN: arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy

## Describe the solution you'd like.
Just attach this managed policy using its ARN to the new role without creating a new IAM policy

## Additional context
[AWS Documentation](https://docs.aws.amazon.com/eks/latest/userguide/csi-iam-role.html)

**Comment by bryantbiggs** [comment]
While that does work for most cases, I don't believe that policy supports encrypted volumes if I remember correctly https://github.com/terraform-aws-modules/terraform-aws-iam/blob/master/modules/iam-role-for-service-accounts-eks/policies.tf#L251

**Comment by obounaim** [comment]
True the managed policy does not give KMS rights.

However, I would still use the AWS policy for basic rights needed by the EBS CSI drive and for KMS I would add a variable attach_ebs_csi_kms_policy to attach a second policy for KMS if needed by the user of the module. 

I think for a lot of use cases, people does not use customer KMS keys to encrypt EBS volumes, that why I would make an option to have KMS rights.

Like this we can achieve :
1. Use a managed policy and make AWS responsible for it
2. Implement least-privilege principal

At least this how I think about it, please let me know what is your opinion about it.

I can make a PR for it if you are OK with it, however this will be a major change for the module.
