### ISSUE TITLE
Unable to register new virtual MFA device with current IAMSelfManagement policy

### ISSUE THREAD

**Issue by rballan** [terraform-aws-modules/terraform-aws-iam#312]
## Description

Last week, AWS release [a new feature for allowing the possibility to assign multiple MFA devices in IAM](https://aws.amazon.com/fr/blogs/security/you-can-now-assign-multiple-mfa-devices-in-iam/). 

This is a great feature, but this modification impact the `MFA resource name` (and `ARN`).

Now, when you want to register a new virtual MFA device, you must enter a name which is used in the MFA device resource name. 

This resource name modification brings a problem : the `IAMSelfManagement policy` not working anymore for register new virtual MFA device. Example with a virtual MFA device named `test` :  

![image](https://user-images.githubusercontent.com/13728714/203302586-4abd849c-8708-4c35-ab57-0b35d0c3264c.png)

# now  

## Expected behavior

Can register a virtual MFA device. 

## Actual behavior

Permissions error when adding a new virtual MFA device.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 5.11.0 :tada:
