### ISSUE TITLE
Add a status variable for the AWS access key in the iam-user module

### ISSUE THREAD

**Issue by simonweil** [terraform-aws-modules/terraform-aws-iam#314]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: It exists for years

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_access_key#status

## Is your request related to a problem? Please describe.

Yes, I need to disable a key but can't via the module, and if I disable manually then when I apply TF again it's reactivated.

## Describe the solution you'd like.

A new variable for the key status

## Describe alternatives you've considered.

None

## Additional context

![Screen Shot 2022-11-23 at 1 17 03](https://user-images.githubusercontent.com/2317562/203440537-27b2cfe5-2625-4bde-b1b6-f2004d5ff309.png)

**Comment by antonbabenko** [comment]
This issue has been resolved in version 5.9.0 :tada:

**Comment by simonweil** [comment]
Thank you guys!
