### ISSUE TITLE
Invalid template interpolation value for autoscaler role

### ISSUE THREAD

**Issue by yaroslav-orel-jfrog** [terraform-aws-modules/terraform-aws-iam#322]
## Description

I added the following to my eks.tf file

```
module "cluster_autoscaler_irsa_role" {
  source = "terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks"

  role_name                        = "cluster-autoscaler"
  attach_cluster_autoscaler_policy = true
  cluster_autoscaler_cluster_ids   = [module.eks.cluster_id]

  oidc_providers = {
    ex = {
      provider_arn               = module.eks.oidc_provider_arn
      namespace_service_accounts = ["kube-system:cluster-autoscaler"]
    }
  }
}
```

When I execute terraform plan I get the following error

```
╷
│ Error: Invalid template interpolation value
│ 
│   on .terraform/modules/cluster_autoscaler_irsa_role/modules/iam-role-for-service-accounts-eks/policies.tf line 83, in data "aws_iam_policy_document" "cluster_autoscaler":
│   83:         variable = "autoscaling:ResourceTag/kubernetes.io/cluster/${statement.value}"
│     ├────────────────
│     │ statement.value is null
│ 
│ The expression result is null. Cannot include a null value in a string template.
```

If your request is for a new feature, please use the `Feature request` template.

 ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: did not specify

- Terraform version:
1.3.6
- Provider version(s):
```
Terraform v1.3.6
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.48.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.16.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4
```

## Reproduction Code [Required]

Mentioned above

Not using workspaces
Cleared the cache, still reproduces
Steps:
```
terraform init
terraform plan
```

## Expected behavior

successful plan that creates autoscaler role for eks

## Actual behavior

error above

### Terminal Output Screenshot(s)

<img width="1281" alt="image" src="https://user-images.githubusercontent.com/59203535/209951130-02ec5985-14a9-48c3-a4f6-221eeed65ad7.png">

## Additional context
-//-

**Comment by mvink-guida** [comment]
with module 19 of terraform eks the output changed from cluster_id  to cluster_name

`cluster_autoscaler_cluster_ids   = [module.eks.cluster_name]`

**Comment by YosraChf** [comment]
You have to change your config like this : 
`module "cluster_autoscaler_irsa_role" {
  source = "terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks"

  role_name                        = "cluster-autoscaler"
  attach_cluster_autoscaler_policy = true
  cluster_autoscaler_cluster_ids   = [module.eks.cluster_name]

  oidc_providers = {
    ex = {
      provider_arn               = module.eks.oidc_provider_arn
      namespace_service_accounts = ["kube-system:cluster-autoscaler"]
    }
  }
}`

and any other thing that references `cluster_id` instead of `cluster_name`
