### ISSUE TITLE
modules/iam-role-for-service-accounts-eks - wrong condition string in IAM policy for EBS driver

### ISSUE THREAD

**Issue by prysmakou-sa** [terraform-aws-modules/terraform-aws-iam#325]
## Description

The condition string for DeleteVolume action has changed in the [example policy of the aws-ebs-csi-driver ](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/ce8a68ba1d2ad5b142edccc52ee09fa82a097965/docs/example-iam-policy.json#L104) and in the (AWS managed) AmazonEBSCSIDriverPolicy.

It must be:
```
{
      "Effect": "Allow",
      "Action": [
        "ec2:DeleteVolume"
      ],
      "Resource": "*",
      "Condition": {
        "StringLike": {
          "ec2:ResourceTag/kubernetes.io/created-for/pvc/name": "*"
        }
      }
    },

```
compare it to[ the current](https://github.com/terraform-aws-modules/terraform-aws-iam/blob/aa7ddba39b658088788652b1a0c3221ccf73cf13/modules/iam-role-for-service-accounts-eks/policies.tf#L223):
```
statement {
    actions   = ["ec2:DeleteVolume"]
    resources = ["*"]

    condition {
      test     = "StringLike"
      variable = "ec2:ResourceTag/kubernetes.io/cluster/*"
      values   = ["owned"]
    }
  }
```
EKS 1.23

aws-ebs-csi-driver-2.11.1 chart (the driver version 1.11.3)

## Steps to reproduce
create PVC following https://github.com/kubernetes-sigs/aws-ebs-csi-driver/tree/master/examples/kubernetes/dynamic-provisioning

Delete the resources

## Expected behavior

Volume deletion without errors

## Actual behavior

EBS controller logs like "DeleteDisk could not delete volume: UnauthorizedOperation: You are not authorized to perform this operation. " 

Example tags:
<img width="807" alt="Screenshot 2023-01-12 at 13 51 54" src="https://user-images.githubusercontent.com/81765132/212074368-814aa664-13a4-4f85-94ae-d04cb9172274.png">

**Comment by prysmakou-sa** [comment]
For the sake of truth I'm able to reproduce the error only on some of my clusters. But the policy in this repo is definitely different from what we have in AWS managed policy and from what we can find in example policy in aws-ebs-csi-driver repo (they also use it for testing purposes)

**Comment by bryantbiggs** [comment]
Yes, it should be updated since the upstream policy was updated (what we intended to track) https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1450
