### ISSUE TITLE
Can not access v5.11.1 release

### ISSUE THREAD

**Issue by igoratencompass** [terraform-aws-modules/terraform-aws-iam#329]
## Description

I'm trying to install the latest [v5.11.1](https://github.com/terraform-aws-modules/terraform-aws-iam/releases/tag/v5.11.1) release but I get:

```
╷
│ Error: Unresolvable module version constraint
│ 
│ There is no available version of module "registry.terraform.io/terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks" (eks.tf:162) which matches the given version constraint. The newest available version is 5.10.0.
╵
```

**Comment by bryantbiggs** [comment]
It looks like the Terraform registry isn't picking up the new release. I know they were changing CDN providers on Wednesday, maybe there's issues from that change

**Comment by dhoppe** [comment]
@bryantbiggs Is it possible to change this via the web interface to fix this at least temporarily?

**Comment by bryantbiggs** [comment]
@antonbabenko would you mind looking on the Terraform registry to see if we can get it to pick up the latest release. It seems like the registry had a moment during the release of v5.1.1

**Comment by antonbabenko** [comment]
Yes, I will be able to do it tomorrow (from laptop).

**Comment by antonbabenko** [comment]
I have just "fixed" it by clicking the resync button in the Terraform Registry, and it helped.
