### ISSUE TITLE
Self-managed policy in iam-group-with-policies does not work for users with path

### ISSUE THREAD

**Issue by enver** [terraform-aws-modules/terraform-aws-iam#334]
## Description

Self-managed policy in iam-group-with-policies does not work for users with path since 5.11.0. Changes introduced removed support for users with path.

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: [v5.11.0+](https://github.com/terraform-aws-modules/terraform-aws-iam/releases/tag/v5.11.0)

- Terraform version:
Terraform v1.3.7
on darwin_amd64
- Provider version(s):
provider registry.terraform.io/hashicorp/aws v4.52.0

## Reproduction Code [Required]

examples/iam-group-with-policies

* After applying the example update path for one of the users to i.e. `/developers/`
* Remove user from `superadmins` group
* NOTE: to workaround issue #332 remove `DenyAllExceptListedIfNoMFA` statement from self managed policies.
* Enable console access
* Login with modified user account
* Try to execute one of the statements from self managed policy. i.e. create IAM access keys

## Expected behavior

Users with path should be able to perform actions granted in self manage policy.

## Actual behavior

An error is returned: `You do not have the permission required to perform this operation. Ask your administrator to add permissions.`

## Additional context
Introduced in PR #313

**Comment by AGirin** [comment]
We are getting the same issue with S3 buckets now. Removing self-managed policy make it all work...

**Comment by AGirin** [comment]
Please re-open this issue.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 5.14.1 :tada:
