### ISSUE TITLE
iam-role-for-service-accounts-eks has invalid policy for new aws accounts when attach_load_balancer_controller_policy = true

### ISSUE THREAD

**Issue by Apollorion** [terraform-aws-modules/terraform-aws-iam#339]
The following two issues are also effecting the policy stored in terraform on this repo

https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2692
https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3046

Basically, the 2 `condition`'s [here](https://github.com/terraform-aws-modules/terraform-aws-iam/blob/master/modules/iam-role-for-service-accounts-eks/policies.tf#L802) are wrong.

**Comment by bryantbiggs** [comment]
I am sorry but I am not following - can you please provide the information requested in the issue template

**Comment by Apollorion** [comment]
https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3046

They are updating the documented load balancer iam policy, which this repo replicates (its even linked [here](https://github.com/terraform-aws-modules/terraform-aws-iam/blob/master/modules/iam-role-for-service-accounts-eks/policies.tf#L639)). Im just doing you a curtsy of letting you know. You guys need to update your policy in `modules/iam-role-for-service-accounts-eks/policies.tf` to match the recommendation of the upstream policy.

**Comment by bryantbiggs** [comment]
ahhh, ok! Now that makes sense - got it! Thank you, I've subscribed to those linked issue/PR

**Comment by Apollorion** [comment]
Just a heads up, they've merged the policy change https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3046

**Comment by michelzanini** [comment]
Hi, they have merged the permissions and I have a PR to update them here. Please have a look. Thanks.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 5.16.0 :tada:
