### ISSUE TITLE
Missing 'complete' example from README

### ISSUE THREAD

**Issue by TimJones** [terraform-aws-modules/terraform-aws-iam#34]
In the README.md of the current master HEAD, the link to the 'complete' example is broken.

It links to [modules/complete](https://github.com/terraform-aws-modules/terraform-aws-iam/tree/master/modules/complete), which doesn't exist in the current HEAD, nor does a `examples/complete`.

A complete example would be very useful is understanding better how these components fit together.

**Comment by antonbabenko** [comment]
Thanks for opening an issue. I have updated README.

I recommend looking into each individual example linked from README to get a good understanding of how all of these components work. All of them are working independently of each other.
