### ISSUE TITLE
support for group and policy path in iam-group-with-assumable-roles-policy

### ISSUE THREAD

**Issue by lesinigo** [terraform-aws-modules/terraform-aws-iam#344]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: please list the AWS provider version which introduced this functionality

The feature is present in `hashicorp/aws` since before v4.0.0 which is the minimum version already required by this module.

## Is your request related to a problem? Please describe.

Currently the `iam-group-with-assumable-roles-policy` puts all its groups and policies in the default IAM path (that is: `/`), it would be nice to have the possibility to specify a custom path.

## Describe the solution you'd like.

A new `path` input variable to specify the path for the IAM group and IAM policy

## Describe alternatives you've considered.

Having everything in the root path would break our current practices

## Additional context

Pull request is coming 👍

**Comment by bryantbiggs** [comment]
resolved in #345
