### ISSUE TITLE
IAM Role is missing an action statement for syncing from SSM (ssm:DescribeParameters)

### ISSUE THREAD

**Issue by jaydeland** [terraform-aws-modules/terraform-aws-iam#347]
https://github.com/terraform-aws-modules/terraform-aws-iam/blob/51eb17cafa82c51e98de6325758afa33b2c05a6a/modules/iam-role-for-service-accounts-eks/policies.tf#LL426C9-L426C9

│ er-aws is not authorized to perform: ssm:DescribeParameters on resource: * because no identity-based policy allows the ssm:DescribeParameters action\n\tstatus code: 400, request id: ff","stacktrace":"github.com/external-secrets/external-secrets/pkg/controllers/e │
│ xternalsecret.(*Reconciler).Reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller.go:190\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/cont │
│ roller.go:122\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:323\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs. │
│ k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:235"}

**Comment by bryantbiggs** [comment]
please provide the information requested in the issue template provided
