### ISSUE TITLE
[iam-eks-role] Support arbitrary test condition for assume role policy

### ISSUE THREAD

**Issue by enver** [terraform-aws-modules/terraform-aws-iam#366]
## Is your request related to a new offering from AWS?
- No

## Is your request related to a problem? Please describe.
Sometimes we need to assign a single role to multiple service accounts or service account names are created dynamically so we might not know them in advance. The current implementation allows us to specify the exact service account names without the possibility to use wildcards.

## Describe the solution you'd like.
Add a variable `assume_role_condition_test` which will default to `StringEquals` for backward compatibility and allow others to override it with `StringLike` condition so they can use wildcards to specify namespace and service account name.

## Describe alternatives you've considered.
None

## Additional context
The same functionality was implemented for iam-role-for-service-account-eks in #201

**Comment by enver** [comment]
Could someone please review #367?

**Comment by antonbabenko** [comment]
This issue has been resolved in version 5.18.0 :tada:
