### ISSUE TITLE
[iam-role-for-service-accounts-eks] statement.value is null for cluster_autoscaler role, potentially also affeccts karpenter role (possible actually an example/documentation issue)

### ISSUE THREAD

**Issue by ForbiddenEra** [terraform-aws-modules/terraform-aws-iam#368]
## Description

When attempting to apply the example cluster_autoscaler role as shown here: https://github.com/terraform-aws-modules/terraform-aws-iam/blob/master/examples/iam-role-for-service-accounts-eks/main.tf#L67, I'm getting the following error:

#### Error Output:
Running `terraform plan`:
```
│ Error: Invalid template interpolation value
│
│   on .terraform/modules/eks.cluster_autoscaler_irsa_role/modules/iam-role-for-service-accounts-eks/policies.tf line 85, in data "aws_iam_policy_document" "cluster_autoscaler":
│   85:         variable = "autoscaling:ResourceTag/kubernetes.io/cluster/${statement.value}"
│     ├────────────────
│     │ statement.value is null
│
│ The expression result is null. Cannot include a null value in a string template.
```

## Versions

- Module version: 5.16.0
- Terraform version: 1.4.4
- Provider version(s):
```
+ provider registry.terraform.io/hashicorp/aws v4.62.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.2
+ provider registry.terraform.io/hashicorp/helm v2.9.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.19.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4
```

## Reproduction Code

Same as example: https://github.com/terraform-aws-modules/terraform-aws-iam/blob/master/examples/iam-role-for-service-accounts-eks/main.tf#L67

```
module "cluster_autoscaler_irsa_role" {
	source      = "terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks"
	version		= "~> 5.16.0"

	role_name                        = "cluster-autoscaler"
	attach_cluster_autoscaler_policy = true
	cluster_autoscaler_cluster_ids   = [module.eks.cluster_id]

	oidc_providers = {
		eks = {
			provider_arn               = module.eks.oidc_provider_arn
			namespace_service_accounts = ["kube-system:cluster-autoscaler"]
		}
	}

	tags = var.tags
}
```

Using `terraform-aws-vpc` and `terraform-aws-eks` to create the underlying resources.

All my other uses of this module are working fine. Looking at the source, this is the only policy using `${statement.value}`: https://github.com/terraform-aws-modules/terraform-aws-iam/blob/master/modules/iam-role-for-service-accounts-eks/policies.tf#L85

I'm not sure if I'm missing something but the value passed to the module for `cluster_uatoscaler_cluster_ids` is shouldn't be `null` ? (Edit: see below post, this statement is incorrect - it indeed would be null)

**Comment by ForbiddenEra** [comment]
Hmm, maybe I AM missing something.. although I'm not sure how the example could ever work though?

The README for `terraform-aws-eks` module says (at https://github.com/terraform-aws-modules/terraform-aws-eks)

```
cluster_id - The ID of the EKS cluster. **Note: currently a value is returned only for local EKS clusters created on Outposts**
```

If this is indeed true than the example would have never worked, except for a local EKS cluster on Outposts?

Perhaps the description mentioning that is outdated or something?

I even found a posted example in another issue (https://github.com/terraform-aws-modules/terraform-aws-eks/issues/801#issuecomment-1079787977) that doesn't mention outposts at all and uses `cluster_id`

The karpenter role also appears to use  `cluster_id`?

From my quick research, it seems like maybe we should just be using `cluster_name`?

I saw a PR for the provider but I don't think it was ever merged?
https://github.com/hashicorp/terraform-provider-aws/pull/27572

If this is the case, without considering the above PR, then maybe the issue is simply a documentation issue?

**Comment by joshuaganger** [comment]
Thanks for posting this ForbiddenEra!  I was trying to add IRSA for Karpenter using this module and ran into exactly the same issue.  I found that in previous versions of the module, `cluster_id `  was defined as "The name/id of the EKS cluster. Will block on cluster creation until the cluster is really ready".  This was changed in version 19 with the reference to Outposts added.  It sounds like `cluster_id` just returned the name, but then an actual id was added for some clusters so that behavior changed.  

Seems maybe also related to this one: https://github.com/hashicorp/terraform-provider-aws/issues/27560

**Comment by ForbiddenEra** [comment]
Yep. that's likely related.

Personally, I have no objections to just set `cluster_id` to name when not outposts, however I might guess that others may from skimming the related issue you linked; I'm not sure if an issue should be opened there regarding that possibility although looking at the v19 upgrade doc, it's pretty clear about the change and reasoning.

Ideally, any fixes should be in the spirit of avoiding future confusion as well. That said, perhaps returning `cluster_name` as `cluster_id` for non-outpost cases would go against that as `cluster_id` technically has nothing to do with `cluster_name` and is a separate value used in other cases. If anything, I feel like the confusion stems from this being the case previously, thus while it might be all well and good for 'convenience' purposes, I'm not sure it's the best idea.

That considered - that means this module (IAM module) isn't 'ready' for version 19; none of the examples have versions pinned - that could've perhaps made the problem more obvious.

Perhaps the examples / any documentation should perhaps be updated to clarify to generally use `cluster_name` with `cluster_id` only for outposts.

Since the main EKS module had a `cluster_id` output that referred to the clusters name previously, then that sounds like much more feasible root-cause than my previous guess, which I admitted was a shot in the dark.

Not everyone might remember or know off the top of their head that there is no cluster ID (unless using outposts, which I'd wager that would only be a small %age of developers) especially when an actual ID is returned for most other resources or at least an ARN; I think that's what hung me up for a second and then I started getting suspicious when I didn't see a `cluster_id` in my outputs which led me to double-check the outputs/docs of the EKS module.

That's why I was pretty well convinced that my `cluster_id` shouldn't have been `null` as the cluster was a running one; indeed that was a oversight on my part where I had either perhaps forgot that `cluster_id` didn't exist for non-outposts or even that I didn't notice the full extent of any recent changes. Especially as I would've recently been on v18 where an `cluster_id` may have been output, even if it was just the cluster name.

So for a fix, should we:
- update the example to use `cluster_name`? If we do this, should we mention to use `cluster_id` for outposts?
- or, should the examples perhaps be pinned to a version so that regardless of future changes, devs shouldn't run into issues like these until someone can update the example for a newer version? At least if someone copies in an example and it doesn't work they can see that the example was created/tested/intended for a certain version?
- do both?

Also; in the actual code of the module, both of these instances (currently autoscaler and karpenter) use the name `cluster_id` specifically as variable names, such as `cluster_autoscaler_cluster_ids` ..

As an aside, one thing I'm curious about is why autoscaler allows an array of clusters and karpenter does not. Perhaps slightly off topic but is there any case where either would use multiple clusters or not? Just thinking for consistency that if neither would obviously allow multiples that they should both use `id` and not `ids` in one place (autoscaler) and `id` in the other (karpenter). And if there's cases where someone would want the role to apply to multiples, then perhaps both should be `ids`. If indeed there's cases where `autoscaler` would be used on multiple and `karpenter` would never, then I guess it's fine to leave it as-is. I can see cases where the `autoscaler` role could be applied to multiple clusters, but I'm not super familiar with karpenter at the moment.

Perhaps the best option I can think of would be to add `_name` and `_names` variables and merge `_names` and `_ids` in the module.

That way you could have examples for both outposts and non-outposts, with `_names` for regular and `_ids` for outposts and it would just work. Also, if someone was using both and wanted the role on both an outpost cluster and a regular cluster, they could have them as two separate lines in their module config which might make it more clear which is which, however, this could also potentially lead to some confusion if someone were to think that the two were handled in a different way when they'd just be merged.

eg.
```
module "cluster_autoscaler_irsa_role" {
	source      = "terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks"
#...
	cluster_autoscaler_cluster_names = [module.mgmt-eks.cluster_name]
	cluster_autoscaler_cluster_ids   = [module.outposts-eks.cluster_id]
# ...
}
```

Maybe an alternative would be to use `_identifiers` instead of `_id`; while `identifier` and `id` seem similar, I feel like at least the `identifier` term could reasonably refer to the name or the id depending on your use-case.

I do think that it might be more confusing to continue to use `_ids` if the norm is going to be that only outposts clusters would ever have that or even switching to `_names`. 

I also think that updating the example to refer to `cluster_name` or at least include a comment about it may be the best first step along with maybe a mention in the `README.md` somewhere as the sub-modules don't have a typical list of inputs/outputs w/descriptions.
