### ISSUE TITLE
`ebs_csi_kms_cmk_ids` misleading should be renamed to `ebs_csi_kms_cmk_arns`

### ISSUE THREAD

**Issue by ChrisJBurns** [terraform-aws-modules/terraform-aws-iam#372]
## Description
I am creating an IRSA user with the following code:

```hcl
  ebs_csi_kms_cmk_ids = [
    aws_kms_key.ebs_kms_key.arn,
    var.ebs_csi_kms_key_ids["key1"],
    var.ebs_csi_kms_key_ids["key2"],
    var.ebs_csi_kms_key_ids["key3"]
  ]
```

But on apply errors with 
```
Error: creating IAM Policy $NAME: MalformedPolicyDocument: Resource $RESOURCE_ID must be in ARN format or "*". status code: 400, request id: $RESOURCE_ID
```

Turns out it was the `arn`'s that was needed not the ID's as it was passing `aws_kms_key.custom_kms_key.key_id` to them, and when i changed to `aws_kms_key.custom_kms_key.arn`, it worked.

maybe change the variable name so folks dont make the same mistake?

**Comment by ChrisJBurns** [comment]
@antonbabenko  Is this a valid issue or shall I close this?

**Comment by ChrisJBurns** [comment]
@antonbabenko  Is this a valid issue or shall I close this?

**Comment by antonbabenko** [comment]
Hi Chris! I don't think we will need to do anything with this issue. Users should always look into examples or source code to figure out the valid values.

My logic with KMS was always the same - "if ARN doesn't work, try ID instead" - no matter how the argument is named, even in AWS Console or CLI.
