### ISSUE TITLE
Registry description out of sync

### ISSUE THREAD

**Issue by rgarrigue** [terraform-aws-modules/terraform-aws-iam#38]
Hi

This module's description page seems out of sync with the content from the README.md here. At least on this "complete" dead link

![image](https://user-images.githubusercontent.com/1872031/66983112-15172d80-f0b8-11e9-897e-ec439d3c29dd.png)

And thanks for the module :-)

**Comment by antonbabenko** [comment]
Fixed already, closing this issue.
