### ISSUE TITLE
aws_iam_role_policy_attachment using count, and list of policy arns change ordering.

### ISSUE THREAD

**Issue by mattops** [terraform-aws-modules/terraform-aws-iam#381]
Issue is described here:

https://github.com/hashicorp/terraform-provider-aws/issues/12536#issuecomment-1549710215

This `count` in this line:

https://github.com/terraform-aws-modules/terraform-aws-iam/blob/1258cbaf8c6a32c15178cbc74dc00503941c32a5/modules/iam-assumable-role-with-oidc/main.tf#L105

**Comment by bryantbiggs** [comment]
please fill in the details requested in the template provided

**Comment by mattops** [comment]
please can we re-open this @bryantbiggs?
