### ISSUE TITLE
Not passing optional fields fails on iam role for cluster autoscaler

### ISSUE THREAD

**Issue by gencarnacao** [terraform-aws-modules/terraform-aws-iam#385]
## Description

Using the module to create an iam role for eks for the cluster autoscaler fails after the introduction of a new parameter and usage of the coalescelist function

- [X ] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: v5.20.0

- Terraform version:
Terraform v1.3.3
on darwin_arm64

- Provider version(s): 
Terraform v1.3.3
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.37.0
+ provider registry.terraform.io/hashicorp/helm v2.8.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.15.0
+ provider registry.terraform.io/hashicorp/random v3.5.1

## Reproduction Code [Required]

module "cluster_autoscaler_role" {
  source             = "terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks"
  role_name          = "my-role-name"
  policy_name_prefix = "policy-"

  attach_cluster_autoscaler_policy = true
  oidc_providers = {
    main = {
      provider_arn               = data.terraform_remote_state.eks.outputs.oidc_provider_arn
      namespace_service_accounts = [ "default:cluster-autoscaler" ]
    }
  }
}

Try to create a role to use with the AWS EKS autoscaler. Make sure to pass none of the culster
## Expected behavior

IAM role should be created.

## Actual behavior

Build fails with error in terraform function.

### Terminal Output Screenshot(s)

│ Error: Error in function call
│ 
│   on .terraform/modules/cluster_autoscaler_role/modules/iam-role-for-service-accounts-eks/policies.tf line 112, in data "aws_iam_policy_document" "cluster_autoscaler":
│  112:     for_each = toset(coalescelist(var.cluster_autoscaler_cluster_ids, var.cluster_autoscaler_cluster_names))
│     ├────────────────
│     │ while calling coalescelist(vals...)
│     │ var.cluster_autoscaler_cluster_ids is empty list of string
│     │ var.cluster_autoscaler_cluster_names is empty list of string
│ 
│ Call to function "coalescelist" failed: no non-null arguments.

**Comment by bryantbiggs** [comment]
they are only optional because you may be using the module to create an IRSA role for cluster-autoscaler, or for VPC CNI, or any of the other addons. However, for cluster-autoscaler to have the appropriate policy, the cluster name(s) are a required value or else the permissions won't be assigned correctly
