### ISSUE TITLE
Error: Invalid template interpolation value

### ISSUE THREAD

**Issue by venatir** [terraform-aws-modules/terraform-aws-iam#386]
```Error: Invalid template interpolation value
on .terraform/modules/aws-eks.irsa_role_for_secrets_store_csi/modules/iam-role-for-service-accounts-eks/main.tf line 33, in data "aws_iam_policy_document" "this":
        values   = ["arn:${local.partition}:iam::${local.account_id}:role${var.role_path}${local.role_name_condition}"]
local.role_name_condition is null
The expression result is null. Cannot include a null value in a string template.
```
This change is the reason @bryantbiggs 
https://github.com/terraform-aws-modules/terraform-aws-iam/blame/9cda42890147ee5c29c2c8eea3352e7f8d7446b9/modules/iam-role-for-service-accounts-eks/main.tf#L10

**Comment by venatir** [comment]
Screenshot as well:

![Screenshot 2023-05-29 at 12 16 39](https://github.com/terraform-aws-modules/terraform-aws-iam/assets/1568005/7551e3d3-d618-499d-bdfa-43ddecc6dfee)

The try allows for a scenario where role_name_condition becomes null.

**Comment by bryantbiggs** [comment]
please provide the details requested in the issue template

**Comment by venatir** [comment]
I debugged it. Seems that you have `"${var.role_name_prefix}*"` and var.role_name_prefix is null by default. 
You cannot use var.role_name_prefix in a string template if it's null. This construct makes var.role_name_prefix mandatory now and breaks compatibility. Alternatively, make it empty string as a default !?

**Comment by venatir** [comment]
> please provide the details requested in the issue template

Sorry, I create an issue straight from the line of code, so the issue template doesn't show. I'll try to find the requested fields.

![Screenshot 2023-05-29 at 12 45 28](https://github.com/terraform-aws-modules/terraform-aws-iam/assets/1568005/7e54b00c-e846-4263-a215-0cbb2a52a1e9)

**Comment by venatir** [comment]
duplicates #383
