### ISSUE TITLE
Feat: Adding variable trusted_role_actions to other sub-modules

### ISSUE THREAD

**Issue by tcharewicz** [terraform-aws-modules/terraform-aws-iam#392]
## Is your request related to a problem? Please describe.
Currently variable trusted_role_actions is only available at sub-module iam-assumable-role.

## Describe the solution you'd like.
 I'd like to have the same variable, in sub modules. For saml sub module default variable will be different.
- iam-assumable-roles
- iam-assumable-role-with-saml
- iam-assumable-roles-with-saml

## Describe alternatives you've considered.
None.

## Additional context
It's useful to use two additional action with STS action:
- sts:SetSourceIdentity
- sts:TagSession

But when you want to use them, you need to add them to all roles in AWS Account.

**Comment by tcharewicz** [comment]
PR https://github.com/terraform-aws-modules/terraform-aws-iam/pull/393

**Comment by antonbabenko** [comment]
This issue has been resolved in version 5.23.0 :tada:
