### ISSUE TITLE
Latest Release Causing Issue with CDKTF 

### ISSUE THREAD

**Issue by sabinayakc** [terraform-aws-modules/terraform-aws-iam#405]
## Description

Latest release is creating problems in CDKTF.

When using this module in a cdktf project, there is an error converting the module to typescript classes.

- [ X] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Doesn't happen in `v5.24.0` 

## Versions

- Module version [Required]: v.5.25.0

- Terraform version: 1.4.0

- Provider version(s): 4.58

## Reproduction Code [Required]

- Create a cdktf project. 
- Add module to `cdtkf.json` like below
```
"terraformModules": [
    {
      "name": "eks-module",
      "source": "terraform-aws-modules/eks/aws",
      "version": "19.15.3"
    },
    {
      "name": "eks-module-irsa",
      "source": "terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks",
      "version": "5.25.0"
    },
  ],
```
- Run `npm run watch`

## Expected behavior
- Module should not have any error after conversion.

## Actual behavior
- Module has error after conversion
### Terminal Output Screenshot(s)
![image](https://github.com/terraform-aws-modules/terraform-aws-iam/assets/13154166/7561a0d2-81aa-4773-a5a2-c47aca6f2c9a)

## Additional context
- This started happening after v5.25.0
- This problem is related to the extra `/*` while setting default value from this commit: https://github.com/terraform-aws-modules/terraform-aws-iam/blob/b6845776e41fe14f01342bcf684573f174e7410d/modules/iam-role-for-service-accounts-eks/variables.tf#L267
- I have been using this module successfully in cdktf for the past year with no problems until v5.25.0
- @yutachaos 

- Do we need to supply a default value for the newly added variable in v5.25.0 or can we remove the extra `/*`? @yutachaos

**Comment by antonbabenko** [comment]
This is solely a CDKTF issue. Please open it there.
