### ISSUE TITLE
 'iam-user' new feature 'policy_arns' not working with 'iam-policy' ARN ouput #246 

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [terraform-aws-modules/terraform-aws-iam#408]
Hi all,

First of all, thank you for these incredible TF modules ! :)

## Description

"policy_arns" parameters in "terraform-aws-modules/iam/aws//modules/iam-user" seems not working as expected when using 'iam-policy' module .arn output 
I don't know if it's due to the "policy_arns" from iam-user or to the "arn" output from iam-policy not formatted the right way, or the usage of both together that create issues

- [x] ✋ I have searched the open/closed issues and my issue is not listed.
--> New iam-user module feature from 1.58.0, no issue found yet !

## Versions

- Module version [Required]:
1.58.0
- Terraform version:
Terraform v1.5.3
- Provider version(s):
provider registry.terraform.io/datadog/datadog v3.28.0
provider registry.terraform.io/hashicorp/aws v4.67.0
provider registry.terraform.io/hashicorp/external v2.3.1
provider registry.terraform.io/hashicorp/local v2.4.0
provider registry.terraform.io/hashicorp/null v3.2.

## Reproduction Code [Required]

```
module "iam-policy-bucket-xxx-local" {
  source  = "terraform-aws-modules/iam/aws//modules/iam-policy"
  version = "5.28.0"

  name        = "xxx-local-policy"
  path        = "/"
  description = "Policy to fully access the specified S3 bucket(s)"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
		{
			"Sid": "S3All",
			"Effect": "Allow",
			"Action": [
        "s3:PutObject",
        "s3:GetObject",
        "s3:ListBucket",
        "s3:GetBucketVersioning",
        "s3:AbortMultipartUpload",
        "s3:ListMultipartUploadParts",
        "s3:ListBucketMultipartUploads",
        "s3:DeleteObject",
        "s3:GetBucketLocation",
        "s3:GetObjectVersion"
			],
			"Resource": [
        "${module.bucket-xxx-local.s3_bucket_arn}",
        "${module.bucket-xxx-local.s3_bucket_arn}/*"
			]
		}
  ]
}
EOF
}

module "xxx-local-user" {
  source  = "terraform-aws-modules/iam/aws//modules/iam-user"
  version = "5.28.0"

  name = "xxx-local"

  force_destroy           = true
  password_reset_required = false

  policy_arns = ["${module.iam-policy-bucket-xxx-local.arn}"]
}
```

- Use code above, tf plan + tf apply

## Expected behavior

- Attach policy to user

## Actual behavior

Error message displayed : 

```
│ Error: Invalid for_each argument
│
│   on .terraform\modules\bucket-xxx.xxx-local-user\modules\iam-user\main.tf line 50, in resource "aws_iam_user_policy_attachment" "this":
│   50:   for_each = var.create_user ? toset(var.policy_arns) : []
│     ├────────────────
│     │ var.create_user is true
│     │ var.policy_arns is list of string with 1 element
│
│ The "for_each" set includes values derived from resource attributes that cannot be determined until apply, and so Terraform cannot determine the full set of keys that will identify the     
│ instances of this resource.
│
│ When working with unknown values in for_each, it's better to use a map value where the keys are defined statically in your configuration and where only the values contain apply-time        
│ results.
│
│ Alternatively, you could use the -target planning option to first apply only the resources that the for_each value depends on, and then apply a second time to fully converge.
```

### Terminal Output Screenshot(s)
![image](https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/assets/8619233/165d9e94-503c-4bd6-9efb-83ea70273f6b)

## Additional context

I don't think it's an ordering issue, i checked the state file and tried with 'depends_on' without success to fix it
the only fix I found was copy/pasted full ARN or concatenated/guessed ARN for 'policy_arns' parameter

Also, not using the 'policy_arn' parameter from 'iam-user' module and using another Terraform step like : 
```
resource "aws_iam_user_policy_attachment" "attach_s3_policy_local" {

  user       = module.xxx-local-user.iam_user_name
  policy_arn = module.iam-policy-bucket-xxx-local.arn
}
```
Make it work perfectly, but we don't use anymore the 'policy_arn' feature which is a shame :/

**Comment by braunsonm** [comment]
This submodule needs the following fix that @bryantbiggs had done last year. Looks like this was missed.

https://github.com/terraform-aws-modules/terraform-aws-iam/pull/250

That would resolve the issue.

**Comment by garyliu-philips** [comment]
having the same issue. please take a look

**Comment by BetterToAutomateTheWorld** [comment]
Hi,

Thank for your work / the PR merged !

But, unfortunately, i'm trying 5.30.0 right now, and having the same issue / error message as before :(

**Comment by mteodori** [comment]
as a workaround I am using https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_user_policy directly rather than the policy_arns var in the same
