### ISSUE TITLE
Add support to create Assume role with web identity

### ISSUE THREAD

**Issue by sppwf** [terraform-aws-modules/terraform-aws-iam#41]
Hi,

Is it possible to add a role that will add support for assume role with Web identity?

Thanks 
Sergiu Plotnicu

**Comment by max-rocket-internet** [comment]
I would also like this. Can I make a PR for this?

It would be great for any EKS users as the assume role policy action must be `sts:AssumeRoleWithWebIdentity`

**Comment by antonbabenko** [comment]
@max-rocket-internet PR is welcome, as usual :)

Thanks!

**Comment by antonbabenko** [comment]
[v2.5.0](https://github.com/terraform-aws-modules/terraform-aws-iam/releases/v2.5.0) has this feature thankfully to @miguelaferreira and his pull-request #37 .
