### ISSUE TITLE
Use amazon-manged AmazonEKS_CNI_Policy, don't create it

### ISSUE THREAD

**Issue by ptimofee** [terraform-aws-modules/terraform-aws-iam#410]
## Versions
terraform: v1.5.4
terraform-aws-modules/vpc/aws: v5.1.1
eks: v19.15.4
iam-role-for-service-accounts-eks: v5.28.0

## Is your request related to a problem? Please describe.
Currently the module creates its own policy and a role for VPC-CNI addon.
Creating a new policy for IPv6 makes sense, but for IPv4 there is already an amazon managed one -  [AmazonEKS_CNI_Policy](https://docs.aws.amazon.com/aws-managed-policy/latest/reference/AmazonEKS_CNI_Policy.html)

## Describe the solution you'd like.
Attach amazon-provided CNI policy for IPv4 instead of creating new one.

## Describe alternatives you've considered.
Creating role via separate role module and attaching policy like
```
  role_policy_arns = {
    policy = "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"
  }
```

## Additional context
N/A

**Comment by bryantbiggs** [comment]
What is the benefit of this approach?

**Comment by ptimofee** [comment]
Well, I'm not sure what is the benefits of the current approach. Can you explain this as well?

For example, eks module doesn't create new policies, but reuses what Amazon provides.

Some things that come to my mind immediately:
- policy deduplication. Why to create duplicates? It's just common sense.
- no need to keep it up to date. If/when amazon updates their AmazonEKS_CNI_Policy (not sure if it ever happened but...) for new AWS EKS release you don't have to keep your copy up to date. This is more practical sense.

**Comment by bryantbiggs** [comment]
There are no tangible benefits to change this at this time

**Comment by ptimofee** [comment]
Wow, closed. I expected some kind of discussion here.

**Comment by bryantbiggs** [comment]
There wasn't much provided to discuss. There isn't anything that prevents someone from using the managed policy with this sub-module, therefore the way its written provides the most value (some organizations do not accept the use of managed policies since the permissions can change without their knowledge). If you wish to have a discussion, please provide some useful facts and data to back up the topic of discussion
