### ISSUE TITLE
Error when running EKS module with submodule iam-assumable-role>5.27

### ISSUE THREAD

**Issue by vladpanainte** [terraform-aws-modules/terraform-aws-iam#420]
## Description

Error when running EKS module with submodule iam-assumable-role>5.27

Terraform 1.5
iam-assumable-role submodule >5.27

I get the following error

`│ Error: creating IAM Role (nghs-qa-tf-eks-worker): MalformedPolicyDocument: Invalid principal in policy: com.amazon.balsa.error.InvalidPolicyException: The passed in policy has a statement with no principals!
│       status code: 400, request id: 08e291cd-0f57-481a-a0bf-2cedf3705683
│ 
│   with module.node_single_role.aws_iam_role.this[0],
│   on .terraform/modules/node_single_role/modules/iam-assumable-role/main.tf line 142, in resource "aws_iam_role" "this":
│  142: resource "aws_iam_role" "this" {`

This is on EKS 1.27 and looks like its removing the principal for EKS node asusme role

`      ~ assume_role_policy    = jsonencode(
          ~ {
              ~ Statement = [
                  ~ {
                      ~ Action    = "sts:AssumeRole" -> [
                          + "sts:TagSession",
                          + "sts:AssumeRole",
                        ]
                      ~ Principal = {
                          + AWS     = []
                          ~ Service = "ec2.amazonaws.com" -> []
                        }
                      - Sid       = "EKSNodeAssumeRole" -> null
                        # (1 unchanged element hidden)
                    },
                ]
                # (1 unchanged element hidden)
            }
        )`

Please advise.
Thanks,
Vlad

**Comment by bryantbiggs** [comment]
please provide the information requested in the standard issue template

**Comment by vladpanainte** [comment]
The issue has been fixed on our side.
