### ISSUE TITLE
Add custom policy to the iam-role-for-service-accounts-eks

### ISSUE THREAD

**Issue by shawnsavour** [terraform-aws-modules/terraform-aws-iam#438]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.
Currently, the Iiam-role-for-service-accounts-eks module only allows attaching pre-defined IAM policies to service accounts. This limitation restricts the flexibility of assigning granular permissions to service accounts, potentially leading to over-privileged access or compromising security.

## Describe the solution you'd like.
To enhance the capabilities of the Iiam-role-for-service-accounts-eks module, I propose implementing the ability to attach custom IAM policies to service accounts. This feature would allow users to define and assign specific permissions tailored to their specific needs, ensuring a more secure and controlled environment for service accounts.

## Describe alternatives you've considered.
Update the TF modules for iam-role-for-service-accounts-eks

**Comment by shawnsavour** [comment]
It is just a small feature. pls accept the pull request 👍

**Comment by bryantbiggs** [comment]
custom policy attachment is already supported https://github.com/terraform-aws-modules/terraform-aws-iam/blob/91c8dbd25d9546d228c2c8030c1463f9b52c9b43/modules/iam-role-for-service-accounts-eks/main.tf#L84

**Comment by shawnsavour** [comment]
> custom policy attachment is already supported
> 
> https://github.com/terraform-aws-modules/terraform-aws-iam/blob/91c8dbd25d9546d228c2c8030c1463f9b52c9b43/modules/iam-role-for-service-accounts-eks/main.tf#L84

Reopen this, because it is not supported the custom resource aws_iam_policy, it only support defined resource aws_iam_policy like ebs policy, karpenter policy, ... Your comment is only policy attachment, not create any custom policy.

[https://github.com/shawnsavour/terraform-aws-iam/blob/5578ad0f5368661b060875f0f4c8995e7ed4ec6e/modules/iam-role-for-service-accounts-eks/policies.tf#L1450-L1483]

**Comment by shawnsavour** [comment]
Custom policy here like this

https://github.com/shawnsavour/terraform-aws-iam/blob/5578ad0f5368661b060875f0f4c8995e7ed4ec6e/modules/iam-role-for-service-accounts-eks/policies.tf#L1453C1-L1483C2

**Comment by shawnsavour** [comment]
@bryantbiggs Please deeply review it, it is the feature to define and add policy statements to custom policy, not only link the predefined policy arns to the role.
