### ISSUE TITLE
New submodule using `aws_eks_pod_identity_association`

### ISSUE THREAD

**Issue by Jeinhaus** [terraform-aws-modules/terraform-aws-iam#443]
## Is your request related to a new offering from AWS?

Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)?
  - Yes ✅: [v5.29.0](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.29.0) introduced [`aws_eks_pod_identity_association`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_pod_identity_association).

## Describe the solution you'd like.

It would be nice to have a submodule for a role to use the new [EKS Pod Identities](https://docs.aws.amazon.com/eks/latest/userguide/pod-identities.html) analogous to the `iam-assumable-role-with-oidc`.
Using EKS pod identities, we no longer have to annotate the service account of the pod with the role's ARN.

## Describe alternatives you've considered.

We could maybe extend the existing `iam-assumable-role-with-oidc` to optionally use pod identities, but I don't think that that is a good solution.

## Additional context

I'd be willing to give it a try to implement this, if this is something you would consider integrating.

**Comment by bryantbiggs** [comment]
https://github.com/terraform-aws-modules/terraform-aws-iam/pull/442#issuecomment-1837467734
