### ISSUE TITLE
Support `aws_eks_pod_identity_association` as an alternative for IRSA roles in `iam-role-for-service-accounts-eks` submodule

### ISSUE THREAD

**Issue by Jeinhaus** [terraform-aws-modules/terraform-aws-iam#444]
## Is your request related to a new offering from AWS?

Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)?
  - Yes ✅: [v5.29.0](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.29.0) introduced [`aws_eks_pod_identity_association`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_pod_identity_association).

## Describe the solution you'd like.

The existing `iam-role-for-service-accounts-eks` submodule is great and simplifies permission handling for a lot of common services running in EKS clusters.
We would like to continue using these same policies, but using EKS Pod Identities instead of IRSA roles (see "Additional context" why).

It would be nice to have an option in the existing module to use Pod Identities instead of IRSA roles.

## Describe alternatives you've considered.

Create another submodule that uses the same policies from `iam-role-for-service-accounts-eks` but uses EKS Pod Identities instead.
This might even be the preferred solution due to the name of the existing submodule.

## Additional context

Currently, adding the annotation of the IRSA role to service accounts is always a bit awkward, because we manage all AWS related things in Terraform while using yaml-based GitOps for anything running inside EKS.
This always creates a gap between these two stacks.

**Comment by bryantbiggs** [comment]
https://github.com/terraform-aws-modules/terraform-aws-iam/pull/442#issuecomment-1837467734

**Comment by Jeinhaus** [comment]
Ah, perfect. Sorry, I didn't see the PR.
