### ISSUE TITLE
5.33.1 in tf registry?

### ISSUE THREAD

**Issue by teedrupp** [terraform-aws-modules/terraform-aws-iam#455]
## Description

Hey Anton, 

I noticed there was a GH release of 5.33.1 last week, but that version hasn't yet shown up in the terraform registry

* https://registry.terraform.io/modules/terraform-aws-modules/iam/aws/latest

The registry still reports 5.33.0.

Is the release to the registry an automated thing that should happen around the time of tagging and release on Github? Apologies in advance if there's always been a delay in the TFR release. This is the first time I've noticed it.

Really appreciate your work. Thanks for all that you do.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

**Comment by antonbabenko** [comment]
I've just fixed it by manually running "resync module" button in the Terraform Registry.
