### ISSUE TITLE
[iam-role-for-service-accounts-eks]: new IAM policy action required for aws-load-balancer-controller v2.7.0

### ISSUE THREAD

**Issue by antoineco** [terraform-aws-modules/terraform-aws-iam#457]
## Is your request related to a problem? Please describe.

A new feature was added to [aws-load-balancer-controller](https://github.com/kubernetes-sigs/aws-load-balancer-controller) in v2.7.0: [mutual TLS authentication support for Ingress](https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3532).

This feature requires a new IAM policy permission: `elasticloadbalancing:DescribeTrustStores`.

## Describe the solution you'd like.

The action can be added to the existing "load_balancer_controller" `aws_iam_policy_document`:

https://github.com/terraform-aws-modules/terraform-aws-iam/blob/cbb39cb23a8182d3864b5d21e94bc289be8a17c5/modules/iam-role-for-service-accounts-eks/policies.tf#L788-L793

**Comment by antonbabenko** [comment]
This issue has been resolved in version 5.34.0 :tada:
