### ISSUE TITLE
[iam-role-for-service-accounts-eks] Using count causes "Can't access attributes"

### ISSUE THREAD

**Issue by s1rc** [terraform-aws-modules/terraform-aws-iam#460]
## Description

Using a count attribute/input even if it is `count = 1` causes referencing `iam-role-for-service-accounts-eks` module resource error: `Can't access attributes on a list of objects. Did you mean to access attribute "iam_role_arn" for a specific element of the list, or across all elements of the list?`

The purpose of the count in this implementation is to enable deployment of this IRSA and accompanying resources based on a variable, e.g. deploy in a staging environment but not production

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: `5.34.0`
- Terraform version: `1.7.3`

- Provider version(s): `5.3.6`

## Reproduction Code [Required]

```
module "test_irsa" {
  count   = 1

  source  = "terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks"
  version = "5.34.0"

  role_name        = "test-role"
  role_policy_arns = {
    policy = "arn:aws:iam::aws:policy/AdministratorAccess"
  }
  oidc_providers = {
    main = {
      provider_arn               = module.eks.oidc_provider_arn
      namespace_service_accounts = [
        "default:test-service-account"
      ]
    }
  }
}
```

- `module.eks.oidc_provider_arn` is a currently deployed EKS cluster
- This pattern above has worked perfectly in other implementations without using count

1. Add count attribute to `iam-role-for-service-accounts-eks` module
2. Run `terraform plan`

## Expected behavior

- Successful plan output

## Actual behavior

- Referencing module resource, e.g. `module.test_irsa.iam_role_arn` results in terraform error: Can't access attributes on a list of objects. Did you mean to access attribute "iam_role_arn" for a specific element of the list, or across all elements of the list?

**Comment by bryantbiggs** [comment]
we already provide a conditional creation variable `create_role` which can be used to toggle resource creation on/off
