### ISSUE TITLE
Inline Policy

### ISSUE THREAD

**Issue by Arwiim** [terraform-aws-modules/terraform-aws-iam#463]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider

Is possible to create an inline-policy within the iam rol?

```
module "iam_assumable_role_admin" {
  source = "../../modules/iam-assumable-role"
  create_role = true
  trusted_role_services = [
    "lambda.amazonaws.com"
  ]
  role_name = "NaranjaDataLakeStack-odlLambdaCreateEMRRole-15O2CRK2MW8HK"

  # --> INLINE POLICY HERE

  }
  ```

**Comment by antonbabenko** [comment]
This issue has been resolved in version 5.40.0 :tada:
