### ISSUE TITLE
Attach managed iam policy to the custom role.

### ISSUE THREAD

**Issue by mmshaikh88** [terraform-aws-modules/terraform-aws-iam#49]
I have successfully created the iam_policy and role described below:

`module "iam_policy_no_billing" {
  source  = "terraform-aws-modules/iam/aws//modules/iam-policy"

  name        = "no_billing"
  path        = "/"
  description = " This policy stops user to manage billing "

  policy = file("policy-json-files/managed/no-billing.json")
}

module "iam_assumable_role_dev_admin" {
  source  = "terraform-aws-modules/iam/aws//modules/iam-assumable-role"
  version = "~> 2.0"

  trusted_role_arns = [
    "arn:aws:iam::XXXXXXXXX:root",
  ]

  create_role = true

  role_name         = "dev_admin"
  role_requires_mfa = false

  custom_role_policy_arns = [
    "arn:aws:iam::aws:policy/AdministratorAccess",
  ]
}

`

How do I attach the managed iam policy to the role?

**Comment by byarbrough** [comment]
@mmshaikh88 you could attach the policy at creation time with the `aws_iam_role` [managed_policy_arns](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_role#managed_policy_arns) argument. Here is the example from the linked documentation, modified to add the managed IAM policy you mentioned.

```terraform
resource "aws_iam_role" "example" {
  name                = "yak_role"
  assume_role_policy  = data.aws_iam_policy_document.instance_assume_role_policy.json # (not shown)
  managed_policy_arns = ["arn:aws:iam::aws:policy/AdministratorAccess"]
}
```
Alternatively, create the iam role and then attach the policy with [aws_iam_role_policy_attachment](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_role_policy_attachment)
