### ISSUE TITLE
CircleCI OIDC provider and role

### ISSUE THREAD

**Issue by simonweil** [terraform-aws-modules/terraform-aws-iam#500]
## Describe the solution you'd like.

Would you accept a pull request implementing CircleCI OIDC provider and role like for GHA?

## Describe alternatives you've considered.

Keeping it to myself, rather than sharing with the community :)

**Comment by simonweil** [comment]
As the PR is open, should we keep this one?

**Comment by antonbabenko** [comment]
We can have a PR for the generic support and close this issue.
