### ISSUE TITLE
Inline Policy Add functionality so that the name can be something personalized

### ISSUE THREAD

**Issue by Arwiim** [terraform-aws-modules/terraform-aws-iam#508]
https://github.com/terraform-aws-modules/terraform-aws-iam/blob/master/examples/iam-assumable-role/main.tf

In the `iam_assumable_role_inline_policy` add functionality so that the name can be something personalized.

**Comment by bryantbiggs** [comment]
highly unlikely we support it - its an inline policy after all, only valid on the role thats using it
