### ISSUE TITLE
Allow empty values for external secrets kms keys, secrets, ssm parameters

### ISSUE THREAD

**Issue by akumar-99** [terraform-aws-modules/terraform-aws-iam#511]
## Is your request related to a new offering from AWS?
No

## Is your request related to a problem? Please describe.
Yes, I am using `terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks` - `5.41.0` with `attach_external_secrets_policy = true`. We can control access using `external_secrets_kms_key_arns`, `external_secrets_secrets_manager_arns` and `external_secrets_ssm_parameter_arns`, and they have default values set. I do not want to allow access to SSM parameters, but it neither supports [] nor ["]. Can we have a feature for it?

## Describe the solution you'd like.
Allow external_secrets_ssm_parameter_arns to take value as []. If [], then do not add policy statement for SSM parameters access.

## Describe alternatives you've considered.
Tried playing with the values.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 6.0.0 :tada:
