### ISSUE TITLE
variables: specify non-nullable where applicable for easier extensibility

### ISSUE THREAD

**Issue by cpboyd** [terraform-aws-modules/terraform-aws-iam#519]
## Is your request related to a new offering from AWS?
No.

## Is your request related to a problem? Please describe.
Setting a variable to `null` will override any `default` set for that variable.
As a result, this requires any module extending these modules to explicitly define its own default rather than falling back to these modules' defaults.

e.g.
```tf
module "iam_assumable_roles" {
  for_each = var.roles
  source   = "terraform-aws-modules/iam/aws//modules/iam-assumable-role"

  trusted_role_actions = try(each.value.trusted_role_actions, ["sts:AssumeRole", "sts:TagSession"])
}
```

## Describe the solution you'd like.
If `nullable = false` is specified like:
```tf
variable "trusted_role_actions" {
  description = "Additional trusted role actions"
  type        = list(string)
  default     = ["sts:AssumeRole", "sts:TagSession"]
  nullable    = false
}
```

This would be better for staying in-sync with changes to defaults that might be made to these modules:
```tf
module "iam_assumable_roles" {
  for_each = var.roles
  source   = "terraform-aws-modules/iam/aws//modules/iam-assumable-role"

  trusted_role_actions = try(each.value.trusted_role_actions, null)
}
```

**Note: `null` is already invalid for `trusted_role_actions` due to its usage within `concat()`:**
```tf
    actions = compact(distinct(concat(["sts:AssumeRole"], var.trusted_role_actions)))
```

## Describe alternatives you've considered.
As mentioned above, you can explicitly state the _**current**_ defaults in any dependent modules, but these defaults may change as necessitated by bug fixes or new features.

## Additional context
N/A

**Comment by bryantbiggs** [comment]
I don't understand why this is valuable - if you specify something as `null` here, your plan will show the values that you are removing due to this. those could be defaults or values you provided

I don't see how this makes extensibility any easier

**Comment by cpboyd** [comment]
@bryantbiggs As mentioned, this fails with an error for any value in `roles` that doesn't have `trusted_role_actions` defined because of https://github.com/hashicorp/terraform/issues/5471:
```tf
module "iam_assumable_roles" {
  for_each = var.roles
  source   = "terraform-aws-modules/iam/aws//modules/iam-assumable-role"

  trusted_role_actions = try(each.value.trusted_role_actions, null)
}
```

If, however, the variable was defined as `nullable = false` then null would revert to whatever has been set as `default`
