### ISSUE TITLE
Could not download modul

### ISSUE THREAD

**Issue by senad-d** [terraform-aws-modules/terraform-aws-iam#521]
## Description

Please provide a clear and concise description of the issue you are encountering, and a reproduction of your configuration (see the `examples/*` directory for references that you can copy+paste and tailor to match your configs if you are unable to copy your exact configuration). The reproduction MUST be executable by running `terraform init && terraform apply` without any further changes.

If your request is for a new feature, please use the `Feature request` template.

- [*] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:
5.0.0
- Terraform version:
1.9.0
- Provider version(s):
5.0

## Reproduction Code [Required]

On terraform init:
Error: Unreadable module directory
 
The directory .terraform/modules/iam_github_oidc_provider/modules/iam-github-oidc-provider could not be read.
This is a bug in Terraform and should be reported.

- Not using workspaces?
- Yes, I cleared the local cache
- I am trying to run terraform init

## Expected behavior

Download module

## Actual behavior

Can't download module

### Terminal Output Screenshot(s)

<img width="1154" alt="image" src="https://github.com/user-attachments/assets/99bf8f12-f494-474b-af85-60150948e684">

**Comment by antonbabenko** [comment]
"This is a bug in Terraform and should be reported" - the error says, but actually please make sure that you specify the source with double slashes in the address and run "rm -rf .terraform" before running it:

```
module "iam_github_oidc_provider" {
  source    = "terraform-aws-modules/iam/aws//modules/iam-github-oidc-provider"

  tags = {
    Environment = "test"
  }
}
```

**Comment by senad-d** [comment]
The issue lies in specifying a module version. 
At first, I tried module version 5.0.0, and it didn't work. However, when I removed it, it started working. So, I tried specifying the latest version 5.44.1, and it also worked.
