### ISSUE TITLE
Update data.aws_iam_policy_document.load_balancer_controller to include latest updates from upstream

### ISSUE THREAD

**Issue by jstewart612** [terraform-aws-modules/terraform-aws-iam#524]
https://github.com/terraform-aws-modules/terraform-aws-iam/blob/master/modules/iam-role-for-service-accounts-eks/policies.tf#L808-L809

https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/install/iam_policy.json has been updated.  The resource at this line needs to be updated to reflect.

This is to support the latest AWS Load Balancer Controller release.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 5.46.0 :tada:
