### ISSUE TITLE
Documentation needs improvement (!)

### ISSUE THREAD

**Issue by tf42src** [terraform-aws-modules/terraform-aws-iam#529]
Trying to create a role with a "federated" principal. Seems impossible.

1. This needs an example:
https://registry.terraform.io/modules/terraform-aws-modules/iam/aws/latest/submodules/iam-assumable-role-with-oidc

2. Trying to use it like this: `resource "iam-assumable-role-with-oidc" "github_actions_eks_role" { .. }`, running `tf init` results in:
```
│ Could not retrieve the list of available versions for provider hashicorp/iam-assumable-role-with-oidc: provider registry registry.terraform.io does not have a
│ provider named registry.terraform.io/hashicorp/iam-assumable-role-with-oidc
```

3. Same issue for `resource "iam_iam-assumable-role-with-oidc" "github_actions_eks_role" { .. }`

4. All links on the fields just link to itself. e.g. [this one](https://registry.terraform.io/modules/terraform-aws-modules/iam/aws/latest/submodules/iam-assumable-role-with-oidc#input_create_role). That's not helpful.

5. Why is there a boolean variable whether to create a role or not (`create_role`)? The whole purpose is to create a role. Doesn't make sense to me.

6. What is the purpose of specifying the number of attached policies (number_of_role_policy_arns)? Also doesn't make sense to me. Should just count itself based on # attached policies.

7. A lot of the other fields are not self-explanatory (e.g. role_path - why is that required?). A simple example how to use would be _so much_ more user friendly.

**Comment by tf42src** [comment]
@bryantbiggs any comment?

**Comment by bryantbiggs** [comment]
I'm not sure what to comment here - it seems like you are not familiar with some of the Terraform module norms and conventions so I would suggest first digging into the Terraform documentation and then starting to look at modules, and then module implementations (not just ours, there are many modules out there and some really well written ones on the registry)

**Comment by tf42src** [comment]
Maybe there are, but the one I am referring to [1] is not. The documentation is pretty much non-existant and what exists partially does not makes sense. Hence I think it can be improved. So why not keep this ticket open and make things better?

[1] `resource "iam-assumable-role-with-oidc" "github_actions_eks_role"`

**Comment by bryantbiggs** [comment]
its there https://github.com/terraform-aws-modules/terraform-aws-iam/tree/master/examples/iam-assumable-role-with-oidc

but what I think you are actually looking for is https://github.com/terraform-aws-modules/terraform-aws-iam/blob/ef31aca0a9ccbc3dda7d63b704ac8487dc9baea6/examples/iam-github-oidc/main.tf#L37

**Comment by tf42src** [comment]
Thanks for the link, but I still don't see how that addresses my original points.

E.g. pick my `5. Why is there a boolean variable whether to create a role or not (create_role)? The whole purpose is to create a role. Doesn't make sense to me.`

Can you explain what `create_role` is for?

**Comment by bryantbiggs** [comment]
It determines whether a role is created or not

**Comment by tf42src** [comment]
> It determines whether a role is created or not

but the whole purpose of the module **is** to create a role:

![Screenshot 2024-11-12 at 3 29 55 pm](https://github.com/user-attachments/assets/bb1fee99-023e-4f9d-9c2f-bbf00c1a1aeb)

https://registry.terraform.io/modules/terraform-aws-modules/iam/aws/latest/submodules/iam-assumable-role-with-oidc
