### ISSUE TITLE
tf plan stuck on Refreshing state...

### ISSUE THREAD

**Issue by aenshin-pp** [terraform-aws-modules/terraform-aws-iam#538]
## Description

 `tf plan` stuck with `Refreshing state...`:
 ```
  module.iam_assumable_role["xxx"].aws_iam_role_policy_attachment.custom[0]: Refreshing state... [id=yyy]
  ```
  
## Versions

- Module version [Required]: 5.39.0

- Terraform version: v1.7.4
- Provider version(s):
```
+ provider registry.terraform.io/alekc/kubectl v2.1.3
+ provider registry.terraform.io/hashicorp/aws v5.40.0
```
## Reproduction Code [Required]

NA

## Expected behavior

do not stuck or show error

## Additional context

I have run it with `TF_LOG=DEBUG terraform refresh` but no additional messages shown. Also stuck.
Now running almost for 2 hours with `TF_LOG=TRACE`.
Any suggestions to debug will be appreciated.

**Comment by aenshin-pp** [comment]
@bryantbiggs hello,

I've added more details here
https://discuss.hashicorp.com/t/tf-plan-stucks-on-refreshing-state/71797

**Comment by bryantbiggs** [comment]
closing since this isn't a module related issue
