### ISSUE TITLE
Failed to execute "terraform apply" on IAM user module

### ISSUE THREAD

**Issue by Gujarats** [terraform-aws-modules/terraform-aws-iam#6]
when I tried the example from `example/iam-user` and execute this command 

```shell
$ terraform init
$ terraform plan
```
I got this error : 

```shel
$ Error: module.iam_user.aws_iam_user_login_profile.this: expected type of password_length to be string
```

How to solve this ?

Iam this terraform version : 

```shell
Terraform v0.11.5
+ provider.aws v1.12.0
```

**Comment by antonbabenko** [comment]
There is an issue about this already in Terraform AWS provider, which is fixed and will be released in v1.13.0 - https://github.com/terraform-providers/terraform-provider-aws/pull/3919
