### ISSUE TITLE
ses_smtp_password is deprecated

### ISSUE THREAD

**Issue by rgarrigue** [terraform-aws-modules/terraform-aws-iam#71]
Hi there,

`ses_smtp_password` should be replaced by `ses_smtp_password_v4`. Here's the doc https://www.terraform.io/docs/providers/aws/r/iam_access_key.html#ses_smtp_password.

Best regards

**Comment by antonbabenko** [comment]
Hi,

This has been just fixed in the module [v2.9.0](https://github.com/terraform-aws-modules/terraform-aws-iam/releases/v2.9.0).
