### ISSUE TITLE
Support for Terraform v0.13

### ISSUE THREAD

**Issue by nikolay** [terraform-aws-modules/terraform-aws-iam#84]
Terraform v0.13 is scheduled to be GA today. Unfortunately, all modules have a limiting requirement to use v0.12. So far, there are no backward-compatibility issues between v0.13 and v0.12, but we don't want to have to fork all of your modules just to allow v0.13 to work.

**Comment by nikolay** [comment]
Terraform v0.13 just got released.

**Comment by antonbabenko** [comment]
Thanks, @nikolay !

[v2.13.0](https://github.com/terraform-aws-modules/terraform-aws-iam/releases/v2.13.0) has been just released with the support of Terraform 0.13 and AWS provider v3.
