### ISSUE TITLE
Support for AWS provider 3

### ISSUE THREAD

**Issue by kty1965** [terraform-aws-modules/terraform-aws-iam#85]
Currently terraform used `aws` provider `~> 2.23`. cannot resolve `aws` provider `3.1.0`.
```terraform
terraform {
  required_version = "~> 0.12.6"

  required_providers {
    aws = "~> 2.23"
  }
}
```

**Comment by antonbabenko** [comment]
[v2.13.0](https://github.com/terraform-aws-modules/terraform-aws-iam/releases/v2.13.0) has been just released with the support of Terraform 0.13 and AWS provider v3.
