### ISSUE TITLE
Can iam-assumable-role-with-oidc allow "ForAnyValue:StringEquals" instead " just a "StringEquals" condition?

### ISSUE THREAD

**Issue by gswallow** [terraform-aws-modules/terraform-aws-iam#92]
I would like to allow two service accounts (cert-manager and external-dns) to make changes to Route 53 records.  I was able to do this by editing the role created by the iam-assumable-role-with-oidc and changing the StringEquals condition to a ForAnyValue:StringEquals condition but if I supply two values to the oidc_fully_qualified_subjects variable, only the last one ends up in the StringEquals condition.

**Comment by chancez** [comment]
You should be able to provide multiple subjects in a list via `oidc_fully_qualified_subjects`, and if any of them match it will allow access. I'm using this today to allow two different service accounts in different namespaces to use the same IAM role.
