### ISSUE TITLE
terraform iam_assumable_role adaption

### ISSUE THREAD

**Issue by Zyntogz** [terraform-aws-modules/terraform-aws-iam#95]
Hey,

we found an "issue" that you already found and implemented in your lambda module: When using the variable "custom_role_policy_arns" the count parameter will be constructed depending on the length of the list contained in "custom_role_policy_arns". This results in an error of terraform that the length of resources cannot be constructed during runtime. For solution of this, i propose to add a new variable and use this during the count statement:

variables.tf
variable "number_custom_role_policy_arns" {
  description = "Number of IAM policies to attach to IAM role"
  type        = number
  default     = 0
}

main.tf
resource "aws_iam_role_policy_attachment" "custom" {
  count = var.create_role ? var.number_custom_role_policy_arns : 0

  role       = aws_iam_role.this[0].name
  policy_arn = element(var.custom_role_policy_arns, count.index)
}

Thanks!

**Comment by antonbabenko** [comment]
Hi again :)

I see what you mean and it makes sense (unfortunately, Terraform is not so smart yet). Pull-request is welcome.

**Comment by Zyntogz** [comment]
Hey :)

i would love to do so, however i cannot push to a new origin branch. What i do:

git push -u origin feature/iam_assumable_role_number_of_policies_fix
...
remote: Permission to terraform-aws-modules/terraform-aws-iam.git denied to Zyntogz.
fatal: unable to access 'https://github.com/terraform-aws-modules/terraform-aws-iam.git/': The requested URL returned error: 403
...

I can do whatever i want, if https or ssh, it stays like that... You may have any idea?

**Comment by antonbabenko** [comment]
You need to fork the repo, make changes, and send a pull request to this repository.

**Comment by antonbabenko** [comment]
Fixed in #96

[v2.26.0](https://github.com/terraform-aws-modules/terraform-aws-iam/releases/v2.26.0) has been just released.

**Comment by yogeek** [comment]
Hello @antonbabenko 

This fix provoked the deletion of hundreds of role_policy_attachments when our terraform automatically retrieved the last version of this module... indeed, as the variable value is "0" by default, our terraform took an empty array and delete all the attachments.
It implies a pretty big number of problems in our multiple account ^^

In our case, we have an fixed ARNs list and we did not have the error mentionned above.
Do you think this default value to 0 can be adapted to avoid such inconvenience ?

**Comment by antonbabenko** [comment]
@yogeek I understand that this change may bring some difficulties to existing users, so I have corrected it during a couple of hours after the release. See this [comment](https://github.com/terraform-aws-modules/terraform-aws-iam/pull/96#issuecomment-719794955) for details.

In short, you need to use version 2 of this module if you can't upgrade to use the changed behavior.

If you can upgrade, use version 3 of this module and update your code respectively.

The problem which this PR was solving can't be solved more elegantly for both existing users (like you, who have static list of ARNs) and for new cases when ARN will have to be computed and Terraform can't handle it.

**Comment by yogeek** [comment]
@antonbabenko ok thank you. We have pinned the version to `<3`  for now.
